import re
import os
import csv
from collections import defaultdict

# 200 exact terms from the text and their potential translations
keyword_dict = {
    "monetary policy": ["金融政策"],
    "interest rate": ["利子率", "金利"],
    "new keynesian": ["ニューケインジアン"],
    "central bank": ["中央銀行"],
    "government spending": ["政府支出"],
    "aggregate euler": ["集計オイラー"],
    "income inequality": ["所得不平等", "所得格差"],
    "aggregate income": ["集計所得", "総所得"],
    "real interest": ["実質利子"],
    "income risk": ["所得リスク"],
    "forward guidance": ["フォワード・ガイダンス"],
    "keynesian cross": ["ケインジアン・クロス"],
    "aggregate demand": ["集計需要", "総需要"],
    "steady state": ["定常状態"],
    "aggregate consumption": ["集計消費", "総消費"],
    "precautionary saving": ["予備的貯蓄"],
    "consumption demand": ["消費需要"],
    "general equilibrium": ["一般均衡"],
    "intertemporal substitution": ["異時点間代替"],
    "optimal monetary": ["最適金融"],
    "fiscal multipliers": ["財政乗数"],
    "labour supply": ["労働供給", "労働の供給"],
    "fiscal policy": ["財政政策"],
    "fiscal multiplier": ["財政乗数"],
    "rate cut": ["利下げ"],
    "increase consumption": ["消費を増やす", "消費の増加"],
    "expected future": ["将来の期待", "期待される将来", "将来期待"],
    "limited asset": ["限定的な資産", "限定的資産", "資産が限定"],
    "inequality countercyclical": ["不平等が反循環的", "反循環的不平等"],
    "profit income": ["利潤所得"],
    "taylor rule": ["テイラー・ルール"],
    "asset markets": ["資産市場"],
    "fall profit": ["利潤の低下", "利潤低下", "利潤の下落"],
    "taylor principle": ["テイラー原理", "テイラーの原理"],
    "precautionary savings": ["予備的貯蓄"],
    "saving motive": ["貯蓄動機"],
    "inequality risk": ["不平等リスク"],
    "becoming hand-to-mouth": ["手元消費になる", "手元消費家計になる"],
    "cyclical risk": ["循環的リスク"],
    "cyclical inequality": ["循環的不平等"],
    "output gap": ["産出ギャップ", "生産ギャップ"],
    "indirect effect": ["間接効果", "間接的効果"],
    "consumption aggregate": ["集計消費"],
    "optimal policy": ["最適政策"],
    "equilibrium mechanism": ["均衡メカニズム"],
    "supply shocks": ["供給ショック"],
    "budget constraint": ["予算制約"],
    "shift curve": ["曲線をシフト", "曲線のシフト"],
    "future consumption": ["将来の消費", "将来消費"],
    "coefficient expected": ["期待係数", "期待される係数"],
    "markets participation": ["市場参加"],
    "demand logic": ["需要の論理", "需要論理"],
    "asset market": ["資産市場"],
    "market clearing": ["市場清算"],
    "income rises": ["所得が上昇", "所得の上昇", "所得増加"],
    "increase aggregate": ["集計変数の増加", "集計的な増加"],
    "hand-to-mouth households": ["手元消費家計"],
    "consumption": ["消費"],
    "income": ["所得"],
    "aggregate": ["集計", "総"],
    "tank": ["TANK"],
    "policy": ["政策"],
    "households": ["家計"],
    "inequality": ["不平等", "格差"],
    "monetary": ["金融"],
    "thank": ["THANK"],
    "risk": ["リスク"],
    "interest": ["利子", "金利"],
    "rank": ["RANK"],
    "keynesian": ["ケインジアン"],
    "rate": ["率", "利子率", "金利"],
    "euler": ["オイラー"],
    "equilibrium": ["均衡"],
    "effect": ["効果", "影響"],
    "fiscal": ["財政"],
    "demand": ["需要"],
    "shocks": ["ショック"],
    "government": ["政府"],
    "future": ["将来", "未来"],
    "bank": ["銀行"],
    "multiplier": ["乗数"],
    "new": ["新しい", "ニュー"],
    "output": ["産出", "生産", "生産量", "産出量"],
    "hank": ["HANK"],
    "real": ["実質"],
    "increase": ["増加", "上昇", "増やす"],
    "economic": ["経済", "経済的"],
    "hand-to-mouth": ["手元消費"],
    "central": ["中央"],
    "spending": ["支出"],
    "journal": ["ジャーナル", "論文誌"],
    "optimal": ["最適", "最適な"],
    "amplification": ["増幅"],
    "supply": ["供給"],
    "curve": ["曲線"],
    "effects": ["効果", "影響"],
    "fall": ["低下", "下落", "減少"],
    "labour": ["労働"],
    "rise": ["上昇", "増加"],
    "precautionary": ["予備的"],
    "cross": ["クロス"],
    "cyclical": ["循環的"],
    "economics": ["経済学"],
    "state": ["状態"],
    "distribution": ["分布", "分配"],
    "means": ["意味する", "手段"],
    "changes": ["変化", "変更"],
    "countercyclical": ["反循環的"],
    "puzzle": ["パズル"],
    "intertemporal": ["異時点間"],
    "shock": ["ショック"],
    "response": ["反応", "応答"],
    "profits": ["利潤"],
    "agents": ["エージェント", "主体"],
    "therefore": ["したがって", "それゆえ"],
    "rises": ["上昇する", "増加する"],
    "motive": ["動機"],
    "taylor": ["テイラー"],
    "expected": ["期待される", "予想される"],
    "inflation": ["インフレ", "インフレーション"],
    "forward": ["フォワード"],
    "determinacy": ["決定性"],
    "prices": ["価格", "物価"],
    "rates": ["率", "利子率", "金利"],
    "representation": ["表現", "記述"],
    "change": ["変化", "変更"],
    "guidance": ["ガイダンス"],
    "household": ["家計"],
    "indirect": ["間接的"],
    "saving": ["貯蓄"],
    "role": ["役割"],
    "equal": ["等しい", "等号"],
    "share": ["シェア", "割合", "共有"],
    "relative": ["相対的"],
    "multipliers": ["乗数"],
    "asset": ["資産"],
    "channel": ["チャネル", "経路"],
    "heterogeneous agent": ["異質的エージェント"],
    "heterogeneous": ["異質的", "異質な"],
    "agent": ["エージェント"],
    "new keynesian model": ["ニューケインジアン・モデル"],
    "representative agent": ["代表的エージェント", "代表的個人"],
    "representative": ["代表的"],
    "saver": ["貯蓄者"],
    "savers": ["貯蓄者"],
    "marginal propensity to consume": ["限界消費性向"],
    "mpc": ["MPC"],
    "intertemporal marginal propensity to consume": ["異時点間限界消費性向"],
    "impc": ["iMPC"],
    "liquidity constraint": ["流動性制約"],
    "borrowing constraint": ["借入制約", "借入不可条件"],
    "idiosyncratic risk": ["固有リスク", "特異的リスク", "固有のリスク"],
    "uninsurable risk": ["保険不可能なリスク"],
    "aggregate shock": ["集計ショック", "マクロショック"],
    "business cycle": ["景気循環"],
    "euler equation": ["オイラー方程式"],
    "utility function": ["効用関数"],
    "discount factor": ["割引因子"],
    "risk aversion": ["リスク回避度"],
    "elasticity of substitution": ["代替弾力性"],
    "frisch elasticity": ["フリッシュ弾力性"],
    "investment": ["投資"],
    "wealth": ["資産", "富"],
    "cyclical inequality": ["循環的不平等"],
    "divine coincidence": ["神の再一致"],
    "deflation": ["デフレ"],
    "nominal interest rate": ["名目利子率"],
    "real interest rate": ["実質利子率"],
    "wage": ["賃金"],
    "real wage": ["実質賃金"],
    "profit": ["利潤"],
    "dividend": ["配当"],
    "taxes": ["税", "税金"],
    "transfers": ["移転"],
    "government debt": ["政府債務"],
    "government bonds": ["政府債券", "国債"],
    "bonds": ["債券"],
    "liquidity": ["流動性"],
    "illiquid assets": ["非流動的資産"],
    "liquid assets": ["流動的資産"],
    "portfolio": ["ポートフォリオ"],
    "fiscal authority": ["財政当局"],
    "wicksellian": ["ヴィクセル的"],
    "price level targeting": ["物価水準ターゲティング"],
    "fiscal theory of the price level": ["物価水準の財政理論"],
    "ftpl": ["FTPL"],
    "indeterminacy": ["非決定性"],
    "sunspot": ["サン・スポット"],
    "log-linearization": ["対数線形化"],
    "difference equation": ["差分方程式"],
    "characteristic polynomial": ["特性多項式"],
    "eigenvalue": ["固有値"],
    "master equation": ["マスター方程式"],
    "tractable": ["扱いやすい", "トラクタブル"],
    "tractability": ["扱いやすさ"],
    "aggregation": ["集計"],
    "dispersion": ["分散", "ばらつき"],
    "variance": ["分散"],
    "skewness": ["歪度"],
    "procyclical": ["順循環的"],
    "acyclical": ["非循環的"],
    "dampening": ["減衰", "抑制"],
    "new keynesian phillips curve": ["ニューケインジアン・フィリップス曲線"],
    "nkpc": ["NKPC"],
    "is curve": ["IS曲線"],
    "monopolistic competition": ["独占的競争"],
    "sticky prices": ["粘着価格", "価格粘着性"],
    "sticky wages": ["粘着賃金", "賃金粘着性"],
    "calvo": ["カルヴォ"],
    "rotemberg": ["ローテンバーグ"],
    "markup": ["マークアップ"],
    "marginal cost": ["限界費用"],
    "phillips curve": ["フィリップス曲線"],
    "welfare": ["厚生"],
    "welfare loss": ["厚生損失"],
    "loss function": ["損失関数"],
    "first-best": ["ファーストベスト"],
    "second-best": ["セカンドベスト"],
    "commitment": ["コミットメント"],
    "discretion": ["裁量"],
    "ramsey": ["ラムゼイ"],
    "complete markets": ["完備市場", "完全市場"],
    "incomplete markets": ["不完備市場", "不完全市場"],
    "insurance": ["保険"],
    "self-insurance": ["自己保険"],
    "perfect foresight": ["完全予見"],
    "rational expectations": ["合理的期待"],
    "transition dynamics": ["移行動学", "遷移過程"],
    "state variable": ["状態変数"],
    "jump variable": ["ジャンプ変数"],
    "aggregate supply": ["集計供給"],
    "production function": ["生産関数"],
    "technology shock": ["技術ショック"],
    "monetary policy shock": ["金融政策ショック"],
    "demand shock": ["需要ショック"],
    "cost-push shock": ["コストプッシュ・ショック"],
    "capital": ["資本"],
    "investment adjustment costs": ["投資調整費用"],
    "tobin's q": ["トービンのq"],
    "user cost of capital": ["資本の使用者費用"],
    "depreciation": ["減価償却"],
    "labor market": ["労働市場"],
    "search and matching": ["サーチ・アンド・マッチング"],
    "unemployment": ["失業"],
    "unemployment risk": ["失業リスク"],
    "job finding rate": ["求職率"],
    "separation rate": ["離職率"],
    "wage rigidity": ["賃金硬直性"],
    "real rigidities": ["実質硬直性"],
    "nominal rigidities": ["名目硬直性"],
    "strategic complementarity": ["戦略的補完性"],
    "strategic substitutability": ["戦略的代替性"],
    "menu costs": ["メニュー・コスト"],
    "zero lower bound": ["ゼロ下限", "ZLB"],
    "liquidity trap": ["流動性の罠"],
    "quantitative easing": ["量的緩和"],
    "balance sheet": ["バランスシート"],
    "credit friction": ["信用の摩擦"],
    "financial intermediary": ["金融仲介機関"],
    "financial accelerator": ["金融アクセラレーター"],
    "collateral": ["担保"],
    "leverage": ["レバレッジ"],
    "default": ["デフォルト"],
    "heterogeneity": ["異質性"],
    "wealth distribution": ["資産分布"],
    "income distribution": ["所得分布"],
    "gini coefficient": ["ジニ係数"],
    "percentile": ["パーセンタイル"],
    "transition matrix": ["推移行列"],
    "markov chain": ["マルコフ連鎖"],
    "persistence": ["持続性"],
    "volatility": ["ボラティリティ"],
    "covariance": ["共分散"],
    "correlation": ["相関"],
    "approximation": ["近似"],
    "first-order": ["1次"],
    "second-order": ["2次"],
    "welfare criteria": ["厚生基準"],
    "utilitarian": ["功利主義的"],
    "social planner": ["社会計画者"],
    "efficiency": ["効率性"],
    "equity": ["公平性"],
    "redistribution": ["再分配"],
    "progressive taxation": ["累進課税"],
    "lump-sum tax": ["一括税"],
    "distortionary tax": ["歪み的税"],
    "subsidy": ["補助金"],
    "automatic stabilizers": ["自動安定化装置"],
    "rule-of-thumb": ["ルール・オブ・サム"],
    "bounded rationality": ["限定合理性"],
    "behavioral": ["行動的"],
    "cognitive discounting": ["認知的割引"],
    "information friction": ["情報の摩擦"],
    "sticky information": ["粘着情報"],
    "rational inattention": ["合理的無関心"],
    "empirical": ["実証的"],
    "quantitative": ["定量的"],
    "calibration": ["キャリブレーション"],
    "estimation": ["推定"],
    "bayesian": ["ベイズ的"],
    "identification": ["識別"],
    "micro data": ["ミクロデータ"],
    "macro data": ["マクロデータ"],
    "panel data": ["パネルデータ"],
    "cross-section": ["横断面"],
    "time series": ["時系列"],
    "model": ["モデル"],
    "equation": ["方程式", "式"],
    "parameter": ["パラメータ"],
    "function": ["関数"],
    "variable": ["変数"],
    "data": ["データ"],
    "result": ["結果"],
    "analysis": ["分析", "解析"],
    "assumption": ["仮定"],
    "framework": ["枠組み", "フレームワーク"],
    "approach": ["アプローチ"],
    "problem": ["問題"],
    "solution": ["解", "解決策"],
    "value": ["価値", "値"],
    "level": ["水準", "レベル"],
    "system": ["システム", "体系"],
    "dynamics": ["動学", "ダイナミクス"],
    "mechanism": ["メカニズム"],
    "literature": ["文献"],
    "evidence": ["証拠"],
    "figure": ["図"],
    "table": ["表"],
    "section": ["セクション", "節"],
    "chapter": ["章"],
    "time": ["時間"],
    "period": ["期", "期間"],
    "price": ["価格", "物価"],
    "cost": ["費用", "コスト"],
    "rent": ["地代", "レント"],
    "firm": ["企業"],
    "consumer": ["消費者"],
    "market": ["市場"],
    "tax": ["税", "税金", "租税"]
}

chapters = ["1", "2", "3", "4", "5", "6", "8"]

results = []

for ch in chapters:
    en_file = f"Bilbiie/textbook-Ch{ch}.qmd"
    ja_file = f"Bilbiie/textbook-Ch{ch}-ja.qmd"
    
    if not os.path.exists(en_file) or not os.path.exists(ja_file):
        continue
        
    with open(en_file, 'r', encoding='utf-8') as f:
        en_content = f.read()
    with open(ja_file, 'r', encoding='utf-8') as f:
        ja_content = f.read()
        
    en_paras = [p.strip() for p in en_content.split('\n\n') if p.strip()]
    ja_paras = [p.strip() for p in ja_content.split('\n\n') if p.strip()]
    
    for kw, expected_ja in keyword_dict.items():
        pattern = re.compile(r'\b' + re.escape(kw) + r'\b', re.IGNORECASE)
        
        matched_en_indices = [i for i, p in enumerate(en_paras) if pattern.search(p)]
        
        if not matched_en_indices:
            continue
            
        found_translations = set()
        
        for idx in matched_en_indices:
            start_idx = max(0, idx - 2)
            end_idx = min(len(ja_paras), idx + 3)
            ja_context = " ".join(ja_paras[start_idx:end_idx])
            
            for ja_term in expected_ja:
                if ja_term in ja_context:
                    found_translations.add(ja_term)
                    
        results.append({
            "Chapter": ch,
            "English Keyword": kw,
            "Used Translations": " | ".join(found_translations)
        })

aggregated = defaultdict(set)
for r in results:
    kw = r["English Keyword"]
    used = [u for u in r["Used Translations"].split(" | ") if u]
    aggregated[kw].update(used)

with open("keywords_summary.csv", "w", encoding="utf-8-sig", newline="") as f:
    writer = csv.writer(f)
    writer.writerow(["English Term", "Japanese Translations Used", "Notes"])
    
    count = 0
    inconsistencies = []
    
    for kw, expected_ja in keyword_dict.items():
        used = aggregated.get(kw, set())
        if used:
            count += 1
            used_str = ", ".join(used)
            notes = ""
            if len(used) > 1:
                notes = "複数の訳語が存在（一貫性の確認を推奨）"
                inconsistencies.append((kw, used_str))
            writer.writerow([kw, used_str, notes])

print(f"Extracted {count} keywords.")
for kw, used_str in inconsistencies:
    print(f"{kw}: {used_str}")
