# Appendix for:

## The New Keynesian Cross

Florin O. Bilbiie

January 2019

#### Abstract

This Appendix outlines derivations accompanying "The New Keynesian Cross".

#### A RANK Derivations

An agent $j$ chooses consumption, asset holdings and leisure solving the standard intertemporal problem:  $\max E_0 \sum_{t=0}^{\infty} \beta^t U\left(C_t^j, N_t^j\right)$ , subject to the sequence of constraints:

$$B_t^j + \Omega_{t+1}^j V_t \le Z_t^j + \Omega_t^j (V_t + P_t D_t) + W_t N_t^j - P_t C_t^j$$

 $C_t^j, N_t^j$  are consumption and hours worked,  $B_t^j$  is the nominal value at end of period to of a portfolio of all state-contingent assets held, except for shares in firms—likewise for  $Z_t^j$ , beginning of period wealth.[^1]  $V_t$  is average market value at time t of shares,  $D_t$  their real dividend payoff and  $\Omega_t^j$  are share holdings. Absence of arbitrage implies that there exists a stochastic discount factor  $Q_{t,t+1}^j$  such that the price at t of a portfolio with uncertain payoff at t+1 is (for state-contingent assets and shares respectively, for an agent j who participates in those markets):
$$
\frac{B_{j,t}}{P_t} = E_t \left[ Q_{t,t+1}^j \frac{Z_{j,t+1}}{P_{t+1}} \right] \text{ and } \frac{V_t}{P_t} = E_t \left[ Q_{t,t+1}^j \left( \frac{V_{t+1}}{P_{t+1}} + D_{t+1} \right) \right],
$${#eq-1}
which iterated forward gives the fundamental pricing equation:  $\frac{V_t}{P_t} = E_t \sum_{i=1}^{\infty} Q_{t,t+i}^j D_{t+i}$ . The riskless gross short-term REAL interest rate  $R_t$  is a solution to:
$$
\frac{1}{R_t} = E_t Q_{t,t+1}^j 
$${#eq-2}
Note that for nominal assets we have the nominal interest rate  $\frac{1}{I_t} = E_t \frac{P_t}{P_{t+1}} Q_{t,t+1}^j$.

[^1]: We distinguish shares from the other assets explicitly since their distribution plays a crucial role in the rest of the analysis.

Substituting the no-arbitrage conditions (1) into the wealth dynamics equation gives the flow budget constraint. Together with the usual 'natural' no-borrowing limit for each state, and anticipating that in equilibrium all agents will hold a constant fraction of the shares (there is no trade in shares)  $\Omega^{j}$  (whose integral across agents is 1), this implies the usual intertemporal budget constraint:
$$
E_t \left[ \frac{P_t}{P_{t+1}} Q_{t,t+1}^j X_{t+1}^j \right] \le X_t^j + W_t N_t^j - P_t C_t^j.
$$
$$\begin{aligned}
X_t^j &= Z_t^j + \Omega^j \left( V_t + P_t D_t \right)\\
&= Z_t^j + \Omega^j \left( E_t \sum_{i=0}^{\infty} P_t Q_{t,t+i}^j D_{t+i} \right)
\end{aligned}$$

$$\begin{aligned}
E_{t} \sum_{i=0}^{\infty} Q_{t,t+i}^{j} C_{t+i}^{j} &\leq \frac{X_{t}^{j}}{P_{t}} + E_{t} \sum_{i=0}^{\infty} Q_{t,t+i}^{j} \frac{W_{t+i}}{P_{t+i}} N_{t+i}^{j}\\
&= E_{t} \sum_{i=0}^{\infty} Q_{t,t+i}^{j} Y_{t+i}^{j}
\end{aligned}$${#eq-3}
where
$$
Y_{t+i}^{j} = \Omega^{j} D_{t+i} + \frac{W_{t+i}}{P_{t+i}} N_{t+i}^{j}
$${#eq-4}
is income of agent $j$. Maximizing utility subject to this constraint gives the first-order necessary and sufficient conditions at each date and in each state:
$$
\beta \frac{U_C\left(C_{t+1}^j\right)}{U_C\left(C_t^j\right)} = Q_{t,t+1}^j
$$
along with (3) holding with equality (or alternatively flow budget constraint holding with equality and transversality conditions ruling out Ponzi games be satisfied:  $\lim_{i\to\infty} E_t \left[Q_{t,t+i}^j Z_{t+i}^j\right] = \lim_{i\to\infty} E_t \left[Q_{t,t+i}^j V_{t+i}\right] = 0$ ). Using (3) and the functional form of the utility function the short-term nominal interest rate must obey:
$$
\frac{1}{R_t} = \beta E_t \left[ \frac{U_C \left( C_{t+1}^j \right)}{U_C \left( C_t^j \right)} \right].
$$

Denote by small letter log deviations from steady-state, except for rates of return (where they denote absolute deviations). Notice that
$$
Q_{t,t+i} = \beta^{i} \frac{U_{C}\left(C_{t+i}^{j}\right)}{U_{C}\left(C_{t}^{j}\right)}
$$
and in steady state:  $Q_i = \beta^i$ . Thus we have
$$
q_{t,t+i}^{j} = \ln \frac{Q_{t,t+i}^{j}}{Q_{i}^{j}} = \ln \frac{U_{C}\left(C_{t+i}^{j}\right)}{U_{C}\left(C_{t}^{j}\right)} = -\sigma^{-1}\left(c_{t+i}^{j} - c_{t}^{j}\right),
$$
where
$$
q_{t,t+i}^j = q_{t,t+1}^j + q_{t+1,t+2}^j + \ldots + q_{t+i-1,t+i}^j
$$
The Euler equation is:
$$
r_t = -E_t q_{t,t+1}^j
$$
Rewrite as
$$
c_t^j = E_t c_{t+1}^j - \sigma r_t
$$
and iterate forward, using  $q_{t,t+i}^{j} = -\sum_{k=0}^{i-1} r_{t+k}$ 
$$
c_t^j = E_t c_{t+i}^j + \sigma E_t q_{t,t+i}^j
$${#eq-5}

Now loglinearize intertemporal budget constraint
$$
E_{t} \sum_{i=0}^{\infty} \beta^{i} \left( q_{t,t+i}^{j} + c_{t+i}^{j} \right) = E_{t} \sum_{i=0}^{\infty} \beta^{i} \left( q_{t,t+i}^{j} + y_{t+i}^{j} \right)
$$
and add to each side  $(\sigma - 1) \sum_{i=0}^{\infty} \beta^i E_t q_{t,t+i}^j$ 
$$
E_{t} \sum_{i=0}^{\infty} \beta^{i} \left( \sigma q_{t,t+i}^{j} + c_{t+i}^{j} \right) = E_{t} \sum_{i=0}^{\infty} \beta^{i} \left( \sigma q_{t,t+i}^{j} + y_{t+i}^{j} \right)
$$
By virtue of the Euler equation the LHS simplifies
$$
\frac{1}{1-\beta}c_t^j = \sigma \sum_{i=0}^{\infty} \beta^i E_t q_{t,t+i}^j + \sum_{i=0}^{\infty} \beta^i E_t y_{t+i}^j
$$

Develop RHS, use  $q_{t,t}^j = 0$ :
$$\begin{aligned}
\frac{1}{1-\beta}c_t^j &= \sigma 
\sum_{i=0}^{\infty} \beta^{i} E_{t} q_{t,t+i}^{j} = 0 - \sum_{i=1}^{\infty} \beta^{i} E_{t} \sum_{k=0}^{i-1} r_{t+k}\\
&= -\frac{\beta}{1-\beta} \sum_{i=0}^{\infty} \beta^{i} E_{t} r_{t+i}
\end{aligned}$$
And replace to obtain (multiplying by  $1 - \beta$ )
$$\begin{aligned}
c_{t}^{j} &= -\sigma\beta \sum_{i=0}^{\infty} \beta^{i} E_{t} r_{t+i} + (1-\beta) \sum_{i=0}^{\infty} \beta^{i} E_{t} y_{t+i}^{j}\\
&= -\sigma\beta r_{t} + (1-\beta) y_{t}^{j} - \sigma\beta \sum_{i=1}^{\infty} \beta^{i} E_{t} r_{t+i} + (1-\beta) \sum_{i=1}^{\infty} \beta^{i} E_{t} y_{t+i}^{j}
\end{aligned}$$

Now replace the expression for expected consumption tomorrow
$$
\beta c_{t+1}^{j} = -\sigma \beta \sum_{i=0}^{\infty} \beta^{i+1} E_{t} r_{t+1+i} + (1-\beta) \sum_{i=0}^{\infty} \beta^{i+1} E_{t} y_{t+1+i}^{j}
$$
to obtain the consumption function in text:
$$
c_t^j = (1 - \beta) y_t^j - \sigma \beta r_t + \beta E_t c_{t+1}^j.
$${#eq-6}

#### **B** TANK Derivations

Consider the TANK model without the assumption of optimal steady-state subsidy, so with positive profits and lack of steady-state consumption insurance. In particular, instead of assuming  $\tau^S = (\varepsilon - 1)^{-1}$  we set it free: using the steady-state pricing condition  $\frac{WN}{PC} = 1 - \Phi$  where I defined the steady-state distortion following Woodford (2003), Chapter 6 as  $\Phi \equiv 1 - \frac{(1+\tau^S)(\varepsilon-1)}{\varepsilon} \in [0;1]$ . A value of 0 corresponds to an undistorted steady-state equilibrium (such as under an optimal subsidy  $\tau^S = (\varepsilon - 1)^{-1}$ ) and the maximum of 1 obtains when the markup tends to infinity and the subsidy s is fixed.[^2] Using this, the profit share in consumption in steady state is:  $\frac{D}{C} = 1 - \frac{(W/P)N}{C} = \Phi$ , and the transfer share  $\frac{T_H}{C} = \frac{\tau^D}{\lambda} \frac{D}{C}$ , delivering the share of H consumption in total:

$$\frac{C_{H}}{C} = \frac{\left(W/P\right)N}{C} + \frac{Transfer^{H}}{C} = 1 - \left(1 - \frac{\tau^{D}}{\lambda}\right)\Phi$$

[^2]: Other distortions such as imperfect labor markets and a wage markup, or distortionary taxation would change the exact expression for  $\Phi$  but neither its interpretation nor the limit result that under appropriately designed taxes it can be eliminated—so  $\Phi$  can be regarded as a general index of supply distortions.

Approximating around this steady state we have profit deviations as share of C, $d_t = (D_t - D)/C$ 
$$
d_t = c_t - (1 - \Phi)(w_t + n_t) = \Phi c_t - (1 - \Phi)w_t.
$$

The approximation of transfers is still $\frac{\tau^D}{\lambda}d_t$ with the wage schedule (aggregating labor supplies and using goods market clearing and production function) $w_t = (\varphi + \gamma) c_t$. Replacing all this in the approximation of H's budget constraint:
$$
\frac{C_H}{C}c_{H,t} = \frac{(W/P)N}{C}(w_t + n_{H,t}) + \frac{\tau^D}{\lambda}d_t
$$
we obtain their consumption function:
$$
c_{H,t} = \chi(\Phi) y_t,
$$
where $\chi(\Phi) \equiv 1 + \varphi\left(1 - \frac{\tau^D}{\lambda}\right) \Upsilon$  with $\Upsilon \equiv \frac{1}{1 + \frac{\tau^D}{\lambda} \frac{\Phi}{1 - \Phi} \frac{\varphi}{\varphi + \gamma}} \in [0; 1]$ 
which shows that our main conclusions and intuition for the benchmark TANK model in text carry through to the case of more general fiscal policy, without full steady-state redistribution and without optimal subsidy.[^3]

[^3]: The more general point about redistribution is as follows: given an income function for H, say  $C_t^H = \Gamma(Y_t) + \mathcal{T}$, a transfer reduces the elasticity of their after-tax income to aggregate income. Letting  $\chi^{\tau} = \frac{\Gamma_t Y}{\Gamma_t \mathcal{T}}$, it follows immediately that as long as  $\mathcal{T} > 0$  we have  $\chi^{\tau} < \chi^0$  and if it is high enough,  $\chi^{\tau} < 1 < \chi^0$, where  $\chi^0$  is the elasticity under zero transfer.

Consider now the case of **decreasing returns** and of a different **labor market** setup, used in Debortoli and Galí (2018), and previously by Galí, Lopez-Salido and Valles (2007): a centralized labor market pooling everybody's labor input and supplying demand-determined labor according to an aggregate wage schedule; the production function is  $Y = N^{\zeta}$  and the individual labor supply optimality conditions are replaced by a wage schedule and a condition stating that everybody works the same hours, in loglinearized form  $\varphi n_t = w_t - \sigma^{-1} c_t$  and  $n_t^H = n_t^S = n_t$ . With this setup the profit function becomes  $d_t = c_t - \zeta (1 - \Phi) (w_t + n_t)$  and the consumption function of H (replacing everything):
$$\begin{aligned}
c_{H,t} &= \tilde{\chi}y_t\\
\tilde{\chi} &= 1 + \left(1 - \frac{\tau^D}{\lambda}\right) \left(\frac{1 - \zeta + \varphi}{\zeta} + \gamma\right) \tilde{\Upsilon} \text{ with } \tilde{\Upsilon} = \frac{1}{1 + \frac{\tau^D}{\lambda} \left(\frac{1}{\zeta(1 - \Phi)} - 1\right)}
\end{aligned}$$
The main insight regarding  $\chi$  carries through: whether it is smaller or larger than 1 depends on the progressivity of taxes, in particular whether $\tau^D$ is smaller or larger than  $\lambda$. Other than that, the main difference is that  $\chi$ (when > 1) is larger ceteris paribus under DRS  $\zeta < 1$, and it is larger under a centralized labor market even with CRS and optimal subsidy  $(1 + \left(1 - \frac{\tau^D}{\lambda}\right)(\varphi + \gamma))$; for instance, with no redistribution with competitive labor market it is 2, and with centralized labor market it is 3.

### C Analytical HANK Derivations

The loglinearized self-insurance Euler equation of S around the symmetric steady-state is:
$$
c_t^S = sE_t c_{t+1}^S + (1-s) E_t c_{t+1}^H - \sigma r_t.
$$

Noticing that we have, as before in TANK, whatever the redistribution scheme determining  $\chi \equiv 1 + \varphi \left(1 - \frac{\tau^D}{\lambda}\right) \leq 1$:
$$
c_t^H = y_t^H = \chi y_t
$$
we obtain the aggregate Euler-IS for my model:
$$
c_{t} = \delta E_{t} c_{t+1} - \sigma \frac{1-\lambda}{1-\lambda \chi} r_{t},
$${#eq-7}
where  $\delta \equiv 1 + (\chi - 1) \frac{1-s}{1-\lambda \chi}.$ 

Using the stochastic discount factor notation, we now have
$$
\sigma q_{t,t+1}^{S} = c_{t}^{S} - sE_{t}c_{t+1}^{S} - (1-s)E_{t}c_{t+1}^{H}
$$
Iterating forward (note: we no longer have $q_{t,t+i}^j = -\sum_{k=0}^{i-1}r_{t+k}$)
$$
c_t^S = s^i E_t c_{t+i}^S - \sigma \sum_{k=0}^{i-1} s^k \left( r_{t+k} - (1-s) E_t c_{t+k}^H \right)$${#eq-8}
$$
c_t^S = s^i E_t c_{t+i}^S + \sigma E_t \sum_{k=0}^{i-1} s^k \left( q_{t,t+k}^S + (1-s) E_t c_{t+k}^H \right)$${#eq-9}

Using the definition of stochastic discount factor:
$$\begin{aligned}
\sigma q_{t,t+i}^{S} =
& c_{t}^{S} - sE_{t}c_{t+1}^{S} - (1-s)E_{t}c_{t+1}^{H} + c_{t+1}^{S} - sE_{t}c_{t+2}^{S} - (1-s)E_{t}c_{t+2}^{H} +\\
& \dots + c_{t+i-1}^{S} - sE_{t}c_{t+i}^{S} - (1-s)E_{t}c_{t+i}^{H}\\
\sigma q_{t,t+i}^{S} + c_{t+i}^{S} =
& c_{t}^{S} + (1-s)E_{t}\sum_{k=1}^{i} \left(c_{t+k}^{S} -c_{t+k}^{H}\right)\end{aligned}
$$

Now loglinearize the intertemporal budget constraint
$$
E_{t} \sum_{i=0}^{\infty} \beta^{i} \left( q_{t,t+i}^{S} + c_{t+i}^{S} \right) = E_{t} \sum_{i=0}^{\infty} \beta^{i} \left( q_{t,t+i}^{S} + y_{t+i}^{S} \right)
$$
Add to each side $$(\sigma - 1) \sum_{i=0}^{\infty} \beta^i E_t q_{t,t+i}^S$$
$$
E_t \sum_{i=0}^{\infty} \beta^i \left( \sigma q_{t,t+i}^S + c_{t+i}^S \right) = E_t \sum_{i=0}^{\infty} \beta^i \left( \sigma q_{t,t+i}^S + y_{t+i}^S \right)
$$
By virtue of the Euler equation the LHS simplifies
$$
\begin{aligned}
\frac{1}{1-\beta}c_{t}^{S} + (1-s)E_{t}\sum_{i=0}^{\infty}\beta^{i}\sum_{k=1}^{i}\left(c_{t+k}^{S} - c_{t+k}^{H}\right) &= \sigma\sum_{i=0}^{\infty}\beta^{i}E_{t}q_{t,t+i}^{S} + \sum_{i=0}^{\infty}\beta^{i}E_{t}y_{t+i}^{S}\\
\frac{1}{1-\beta}c_{t}^{S} + \frac{1-s}{1-\beta}E_{t}\sum_{i=1}^{\infty}\beta^{i}\left(c_{t+i}^{S} - c_{t+i}^{H}\right) &= \sigma\sum_{i=0}^{\infty}\beta^{i}E_{t}q_{t,t+i}^{S} + \sum_{i=0}^{\infty}\beta^{i}E_{t}y_{t+i}^{S}
\end{aligned}$$

Develop RHS $\sum_{i=0}^{\infty}\beta^{i}E_{t}q_{t,t+i}^{S}$ using $q_{t,t} = 0$; this is as above in general case and replace to obtain (multiplying by $1-\beta$)

$$c_{t}^{S} = -(1-s) E_{t} \sum_{i=1}^{\infty} \beta^{i} \left( c_{t+i}^{S} - c_{t+i}^{H} \right) - \sigma \beta \sum_{i=0}^{\infty} \beta^{i} E_{t} r_{t+i} + (1-\beta) \sum_{i=0}^{\infty} \beta^{i} E_{t} y_{t+i}^{S}$$

$$= -\sigma \beta r_{t} + (1-\beta) y_{t}^{S} - (1-s) E_{t} \sum_{i=1}^{\infty} \beta^{i} \left( c_{t+i}^{S} - c_{t+i}^{H} \right) - \sigma \beta \sum_{i=1}^{\infty} \beta^{i} E_{t} r_{t+i} + (1-\beta) \sum_{i=1}^{\infty} \beta^{i} E_{t} y_{t+i}^{S}$$

Now replace expression for expected consumption tomorrow

$$\beta c_{t+1}^S = -(1-s) E_t \sum_{i=1}^{\infty} \beta^{i+1} \left( c_{t+i+1}^S - c_{t+i+1}^H \right) - \sigma \beta \sum_{i=0}^{\infty} \beta^{i+1} E_t r_{t+1+i} + (1-\beta) \sum_{i=0}^{\infty} \beta^{i+1} E_t y_{t+1+i}^S
$$

to obtain the consumption function:

$$c_t^S = -\sigma \beta r_t + (1 - \beta) y_t^S - (1 - s) E_t \sum_{i=1}^{\infty} \beta^i \left( c_{t+i}^S - c_{t+i}^H \right) - \sigma \beta \sum_{i=1}^{\infty} \beta^i E_t r_{t+i} + (1 - \beta) \sum_{i=1}^{\infty} \beta^i E_t y_{t+i}^S$$

or in recursive form:

$$c_{t}^{S} = -\sigma \beta r_{t} + (1 - \beta) y_{t}^{S} - (1 - s) \beta \left( E_{t} c_{t+1}^{S} - E_{t} c_{t+1}^{H} \right) + \beta E_{t} c_{t+1}^{S}$$
$$= -\sigma \beta r_{t} + (1 - \beta) y_{t}^{S} + \beta s E_{t} c_{t+1}^{S} + \beta (1 - s) E_{t} c_{t+1}^{H}$$

Aggregate and use $c_t^H=y_t^H=\chi y_t$ to obtain (using the notation for $\delta = \frac{s+(1-\lambda-s)\chi}{1-\lambda}$)
$$
c_t = \left[1 - \beta \left(1 - \lambda \chi\right)\right] y_t - \left(1 - \lambda\right) \sigma \beta r_t + \beta \delta \left(1 - \lambda \chi\right) E_t c_{t+1}.
$$
To find the effects of FG we iterate forward:
$$
c_{t} = -(1 - \lambda) \sigma \beta \sum_{i=0}^{\infty} \left[\beta \delta (1 - \lambda \chi)\right]^{i} E_{t} r_{t+i} + \left[1 - \beta (1 - \lambda \chi)\right] \sum_{i=0}^{\infty} \left[\beta \delta (1 - \lambda \chi)\right]^{i} E_{t} y_{t+i}
$$