<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.27">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>textbook-ch6</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="textbook-Ch6_files/libs/clipboard/clipboard.min.js"></script>
<script src="textbook-Ch6_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="textbook-Ch6_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="textbook-Ch6_files/libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="textbook-Ch6_files/libs/quarto-html/popper.min.js"></script>
<script src="textbook-Ch6_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="textbook-Ch6_files/libs/quarto-html/anchor.min.js"></script>
<link href="textbook-Ch6_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="textbook-Ch6_files/libs/quarto-html/quarto-syntax-highlighting-ed96de9b727972fe78a7b5d16c58bf87.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="textbook-Ch6_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="textbook-Ch6_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="textbook-Ch6_files/libs/bootstrap/bootstrap-d6a003b94517c951b2d65075d42fb01b.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="fullcontent quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">




<section id="heterogeneous-agent-macroeconomics" class="level2">
<h2 class="anchored" data-anchor-id="heterogeneous-agent-macroeconomics">Heterogeneous Agent Macroeconomics</h2>
</section>
<section id="a-tractable-new-keynesian-perspective" class="level2">
<h2 class="anchored" data-anchor-id="a-tractable-new-keynesian-perspective">A Tractable New Keynesian Perspective</h2>
<p>Florin O. Bilbiie</p>
<p>University of Cambridge &amp; CEPR</p>
<p>Forthcoming, MIT Press</p>
<p>First version 2019, this version November 2025</p>
<section id="chapter-61" class="level4">
<h4 class="anchored" data-anchor-id="chapter-61">Chapter 6<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a></h4>
<p>Preliminary and Incomplete. Comments Requested</p>
<p>© Florin O. Bilbiie 2019</p>
</section>
</section>
<section id="chapter-6-illiquidity-unequal-saving-and-physical-capital-investment-multiplier-accelerator-redux" class="level1">
<h1>Chapter 6: Illiquidity, Unequal Saving, and Physical Capital Investment: Multiplier-Accelerator Redux</h1>
<p>In this chapter, we consider an important extension of the THANK model developed in chapters 4 and 5. We add investment in physical capital to the model, and show the complementarity between income and wealth inequality in generating aggregate-demand amplification.</p>
<p>In our THANK model studied so far, and indeed in the textbook treatment of the RANK model, we have abstracted from physical capital. Nevertheless, capital plays a central role in macroeconomics and the study of business cycles. For instance, a key feature of Real Business Cycle models is that capital investment is approximately 4 times as volatile as GDP.</p>
<p>However, the recent growth of the HANK literature has prompted a reappraisal of the role of capital in New Keynesian models. In the model developed by Bilbiie et al.&nbsp;(2022), we will see that heterogeneity moves capital to the forefront in determining the consumption response to monetary policy shocks. Crucially, the model isolates two amplification channels for monetary policy. The first channel is the cyclical income inequality channel - the focus of our THANK model analysis thus far. The addition of capital leads to a second capital inequality channel, which resuscitates the Samuelson (1939) multiplier-accelerator. We will see that these channels are complementary in amplifying monetary policy in the model, with the joint effects of capital and income inequality exceeding the individual effects combined.</p>
<section id="a-tale-of-two-inequalities" class="level4">
<h4 class="anchored" data-anchor-id="a-tale-of-two-inequalities">A Tale of Two Inequalities</h4>
<p>To examine the complementarity between capital and income inequality, we will first consider a simple heterogeneous-agent model. In this framework, the budget constraint of household j is given by: <span class="math display">\[C^{j} + S^{j} = (WN)^{j} + (rK + D)^{j} + T^{j} \equiv Y^{j}.\]</span> Above, <span class="math inline">\(C^{j}\)</span> denotes the consumption of household j, while <span class="math inline">\(S^j\)</span> represents the household’s savings. Household savings are in physical capital, which is denoted by <span class="math inline">\(K\)</span>. The household earns labour income <span class="math inline">\((W N)^{j}\)</span> as well as financial income from the return on capital <span class="math inline">\(rK\)</span> and dividends <span class="math inline">\(D\)</span>.</p>
<p>The budget constraint highlights the two sources of inequality in the model. Firstly, in the THANK model without capital, the budget constraint would be given by: <span class="math display">\[C^j = (WN)^j + D^j + T^j \equiv Y^j.\]</span> Here, households differ in their consumption expenditures and their income. This income inequality was the key focus of our analysis of the THANK model. Conversely, in the model with capital, households also have heterogeneous savings capital inequality. To isolate the capital inequality channel, we can assume that transfers ensure that incomes are equal across households. This gives the following budget constraint: <span class="math display">\[C^j + S^j = Y.\]</span></p>
</section>
<section id="a-simple-heterogeneous-agent-model-with-capital" class="level4">
<h4 class="anchored" data-anchor-id="a-simple-heterogeneous-agent-model-with-capital">A Simple Heterogeneous-Agent Model with Capital</h4>
<p>As in the THANK model, consider an economy populated by two types of household. A share <span class="math inline">\(\lambda\)</span> of the households are hand-to-mouth (H), who consume all of their income. The remaining share <span class="math inline">\(1 - \lambda\)</span> are savers (S), who consume and save in physical capital. Loglinearising the model around the symmetric steady state yields the Euler equation:<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a> <span class="math display">\[c_t^S = E_t c_{t+1}^S - r_t.\]</span> Loglinearising the household budget constraints gives: <span class="math display">\[\begin{aligned}
C_Y c_t^S + \frac{I_Y}{1 - \lambda} i_t &amp;= Y_Y^S y_t^S\\
c_t^H &amp;= y_t^H = \chi y_t
\end{aligned}\]</span> where <span class="math inline">\(i_t\)</span> denotes investment and <span class="math inline">\(\chi\)</span> is the elasticity of hand-to-mouth income to aggregate income. <span class="math inline">\(X_Y\)</span> denotes the steady state of a variable as a share of steadystate output.</p>
<p>For simplicity, we will initially assume that households follow an exogenous isoelastic investment function: <span class="math display">\[i_t = \eta y_t.\]</span> Aggregate consumption and investment and given by: <span class="math display">\[\begin{aligned}
c_t &amp;= \lambda c_t^H + (1 - \lambda)c_t^S\\
y_t &amp;= \lambda Y_Y^H y_t^H + (1 - \lambda)Y_Y^S y_t^S.
\end{aligned}\]</span> Goods market clearing requires that: <span class="math display">\[y_t = C_Y c_t + I_Y i_t.\]</span></p>
<p>To isolate the role of capital inequality, consider the case with <span class="math inline">\(\chi = 1\)</span> such that the income inequality channel offers no amplification of monetary policy. An implication of this case is that households’ incomes are proportional, meaning that <span class="math inline">\(y_t = y_t^S = y_t^H\)</span>. From the equation for aggregate consumption, we can express the consumption of savers as: <span class="math display">\[c_t^S = \frac{c_t - \lambda c_t^H}{1 - \lambda} = \frac{c_t - \lambda y_t}{1 - \lambda}.\]</span> From the goods market clearing condition, we have: <span class="math display">\[c_t = \frac{y_t - I_Y i_t}{C_Y}.\]</span> The steady-state goods market cleaaring condition gives us: <span class="math display">\[C_Y + I_Y = 1.\]</span> We can therefore use the investment function to express aggregate consumption as: <span class="math display">\[c_t = \frac{1 - \eta I_Y}{1 - I_Y} y_t.\]</span></p>
<p>Substituting these equations into the savers’ Euler equation yields the aggregate Euler equation: <span class="math display">\[c_t = E_t c_{t+1} - \underbrace{\frac{1 - \lambda}{1 - \lambda \frac{1 - I_Y}{1 - \eta I_Y}}}_{\text{Multiplier}} r_t.\]</span> In this model, we can see that the consumption response to a one-time real interest rate change is given by: <span class="math display">\[\left| \frac{\partial c_t}{\partial r_t} \right|_{K\text{ inequality}} = \frac{1 - \lambda}{1 - \lambda \frac{1 - I_Y}{1 - \eta I_Y}}.\]</span> Recall that the aggregate Euler equation for the RANK model featured a unit coefficient on the real interest rate. The introduction of capital therefore introduces another Keynesian-cross multiplier and amplifies the effect of monetary policy if and only if <span class="math inline">\(\eta &gt; 1\)</span>. This condition requires that investment is procyclical and more volatile in output. Hence, well documented business cycle statistics show that the condition will be satisfied in reality.</p>
<p>The multiplier is present because the investment of the savers generates income which is partly received by hand-to-mouth households. When savers invest, aggregate income rises due to the increase in capital income. A portion of this rise in income will accrue to hand-to-mouth households. This redistribution could take place directly through the tax system, or indirectly through a rise in labour demand leading to increased labour income for H households. The rise in income causes H households to increase their consumption, leading to a further rise in income. Savers invest a proportion <span class="math inline">\(\eta\)</span> of this rise in income, causing a further round of income increases. This leads to a Keynesian-cross multiplier summarised by the term <span class="math inline">\(\frac{1-I_Y}{1-\eta I_Y}\)</span>, and essentially follows the logic of the Samuelson (1939) multiplier-accelerator.</p>
</section>
<section id="aggregate-demand-complementarity-the-multiplier-of-the-multiplier" class="level3">
<h3 class="anchored" data-anchor-id="aggregate-demand-complementarity-the-multiplier-of-the-multiplier">Aggregate Demand Complementarity: ‘The Multiplier of the Multiplier’</h3>
<p>In the above section, we have shown that the inclusion of capital inequality amplifies the consumption effects of monetary policy, even in the case with proportional incomes. Reintroducing countercyclical income inequality gives a multiplier of: <span class="math display">\[\left|\frac{\partial c_t}{\partial r_t}\right|_{K \&amp; Y\text{ inequality}} = \frac{1-\lambda}{1-\lambda\chi\frac{1-I_Y}{1-\eta I_Y}}.\]</span></p>
<p>Importantly, provided that investment is sufficiently procyclical <span class="math inline">\((\eta &gt; 1)\)</span> and hand-tom-mouth income is more volatile than aggregate income <span class="math inline">\((\chi)\)</span>, we can see that income and capital inequality interact to generate amplification which is greater than the two inequality channels combined. To see this complementarity, recall that the multiplier for the model with only income inequality is: <span class="math display">\[\left| \frac{\partial c_t}{\partial r_t} \right|_{Y\text{ inequality}} = \frac{1 - \lambda}{1 - \lambda \chi}.\]</span> We can therefore see that: <span class="math display">\[\begin{aligned}
\left| \frac{\partial c_t}{\partial r_t} \right|_{K \&amp; Y\text{ inequality}} &amp;&gt; \left| \frac{\partial c_t}{\partial r_t} \right|_{K\text{ inequality}} \times \left| \frac{\partial c_t}{\partial r_t} \right|_{Y\text{ inequality}} \\
\frac{1-\lambda}{1-\lambda\chi\frac{1-I_Y}{1-\eta I_Y}} &amp;&gt; \frac{1-\lambda}{1-\lambda\frac{1-I_Y}{1-\eta I_Y}} \times \frac{1-\lambda}{1-\lambda\chi}
\end{aligned}\]</span> if <span class="math inline">\(\eta &gt; 1\)</span> and <span class="math inline">\(\chi &gt; 1\)</span>. Capital inequality serves to amplify the effects of income inequality, serving as a ‘multiplier of the multiplier’. Recall that the numerator of the multiplier represents the ‘direct effect’ of the interest rate change, with a mass <span class="math inline">\(1 - \lambda\)</span> of savers increasing consumption due to intertemporal substitution following an interest rate cut. The denominator represents the indirect effects of interest rate changes. Therefore, the multiplier for the model with both capital and income inequality shows that the indirect effects interact nonlinearly in each round, and act as multipliers of each other.</p>
<p>When savers invest, aggregate income rises. When <span class="math inline">\(\chi &gt; 1\)</span>, the income of the hand-to-mouth households rises more than one-for-one with aggregate income. This leads to a rise in H households’ consumption demand and a further rise in aggregate income. When <span class="math inline">\(\eta &gt; 1\)</span>, the savers respond to this rise in aggregate income by increasing investment further, beginning another round of consumption increases.</p>
<section id="simple-testable-predictions" class="level4">
<h4 class="anchored" data-anchor-id="simple-testable-predictions">Simple Testable Predictions</h4>
<p>This simple TANK model with capital inequality yields two testable predictions. Firstly, we can express income and consumption inequality as: <span class="math display">\[\begin{aligned}
y_t^S - y_t^H &amp;= \frac{1 - \chi}{(1 - \lambda)Y_Y^S} y_t\\
c_t^S - c_t^H &amp;= \frac{1 - \chi C_Y - \eta I_Y}{(1 - \lambda)C_Y} y_t.
\end{aligned}\]</span> Income inequality is countercyclical when <span class="math inline">\(\chi &gt; 1\)</span>. Consumption inequality is countercyclical if and only if: <span class="math display">\[C_Y(\chi - 1) + I_Y(\eta - 1) &gt; 0.\]</span> This means that, given that investment is more than one-to-one procyclical, consumption inequality can be countercyclical even in the case where income inequality is not.</p>
<p>Secondly, consumption inequality is more countercyclical than income inequality if <span class="math inline">\(\eta &gt; 1\)</span>. This theoretical prediction is consistent with recent empirical studies. For instance, Coibion et al.&nbsp;(2017) use US consumer survey data to show that expenditure inequality rises more than income inequality following a contractionary monetary policy shock. This suggests that consumption inequality is indeed more countercyclical than income inequality.</p>
</section>
<section id="policy-implications-determinacy-and-forward-guidance" class="level4">
<h4 class="anchored" data-anchor-id="policy-implications-determinacy-and-forward-guidance">Policy Implications: Determinacy and Forward Guidance</h4>
<p>We can also amend our simple model to consider the implications of capital inequality for determinacy and forward guidance. Suppose now, as in the THANK model, that households face idiosyncratic income risk, with savers becoming handto-mouth next period with probability <span class="math inline">\(1 - s\)</span>. The self-insurance Euler equation in this case is: <span class="math display">\[c_t^S = sE_t c_{t+1}^S + (1-s)E_t c_{t+1}^H - r_t.\]</span> This simple THANK model yields and aggregate Euler equation:</p>
<p><span class="math display">\[\begin{aligned}
c_t &amp;= \Theta E_t c_{t+1} - \Omega r_t\\
\text{where } \Theta &amp;\equiv 1 + (1 - s) \frac{\chi \frac{1 - I_Y}{1 - \eta I_Y} - 1}{1 - \lambda \chi \frac{1 - I_Y}{1 - \eta I_Y}}\\
\text{and } \Omega &amp;\equiv \frac{1 - \lambda}{1 - \lambda \chi \frac{1 - I_Y}{1 - \eta I_Y}}.
\end{aligned}\]</span></p>
<p>In order for the model to generate compounding of news shocks, the coefficient on expected consumption must be greater than one. This requires that: <span class="math display">\[\begin{aligned}
\chi \frac{1 - I_Y}{1 - \eta I_Y} &amp;&gt; 1\\
\Rightarrow \eta &amp;&gt; 1 + (1 - \chi) \frac{1 - I_Y}{I_Y}.
\end{aligned}\]</span> When investment is sufficiently procyclical, the model with capital inequality will generate compounding. With procyclical investment, a ‘good news shock’ about future aggregate output will lead to a larger rise in future investment. This investment will lead to a rise in future aggregate income, and a rise in the future income of the hand-to-mouth households. As a result, the precautionary saving motive is weakened and households increase present consumption by more in response to the expected future shock.</p>
<p>As was the case in the THANK model with only income inequality, the compounding of news shocks has important implications for the forward guidance puzzle and the requirements for determinacy under an interest rate rule.</p>
<p>The present consumption response to an announced interest rate cut in period <span class="math inline">\(t + T\)</span> is given by: <span class="math display">\[\frac{\partial c_t}{\partial (-r_{t+T})} = \Theta^T \Omega.\]</span> When investment is sufficiently procyclical such that <span class="math inline">\(\Omega &gt; 1\)</span>, the consumption response to the interest rate cut will be increasing in its horizon. Introducing capital inequality therefore means that the forward guidance puzzle can persist even in the case with acyclical or procyclical income inequality. Hence, the result that procyclical income inequality solves the forward guidance puzzle does not necessarily generalise to our setting with both income and capital inequality.</p>
<p>To analyse the implications of capital inequality for determinacy, suppose that the central bank sets nominal interest rates according to a Taylor rule, and introduce a simple static Phillips curve: <span class="math display">\[\begin{aligned}
r_t^n \equiv r_t + E_t \pi_{t+1} &amp;= \phi_\pi \pi_t\\
\pi_t &amp;= \kappa c_t.
\end{aligned}\]</span> Substitute these equilibrium conditions into the aggregate Euler equation to obtain: <span class="math display">\[c_t = \frac{\Theta + \kappa \Omega}{1 + \phi_\pi \kappa \Omega} E_t c_{t+1}.\]</span> For determinacy under a Taylor rule, the coefficient on expected consumption must be less than one. This gives the following condition on <span class="math inline">\(\phi_\pi\)</span>: <span class="math display">\[\phi_{\pi} &gt; 1 + \frac{\Theta - 1}{\kappa \Omega}.\]</span></p>
<p>The condition for determinacy therefore becomes more stringent than the Taylor principle (<span class="math inline">\(\phi_\pi &gt; 1\)</span>) when investment is sufficiently procyclical such that <span class="math inline">\(\Theta &gt; 1\)</span>. The capital inequality channel weakens the endogenous dampening from precautionary saving and idiosyncratic risk, and leads to compounding of news shocks. The central bank must therefore respond more strongly to rises in inflation in order to prevent sunspots from becoming self fulfilling.</p>
</section>
<section id="a-tractable-hank-with-capital" class="level4">
<h4 class="anchored" data-anchor-id="a-tractable-hank-with-capital">A Tractable HANK with Capital</h4>
<p>To quantify the effects of and complementarity between capital and income inequality channels, Bilbiie et al.&nbsp;(2022) develop a THANK model with illiquid capital.<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a> As in the THANK model with only income inequality, households face idiosyncratic risk such that the stationary share of hand-to-mouth households is again given by: <span class="math display">\[ \lambda = \frac{1-s}{2-s-h}. \]</span></p>
<p>Households can save in liquid bonds, illiquid shares, or illiquid capital. The evolution of capital is given by: <span class="math display">\[K_{t+1} = (1 - \delta)K_t + \Phi\left(\frac{I_t}{K_t}\right)K_t\]</span> where the function <span class="math inline">\(\Phi()\)</span> represents capital adjustment costs. Wages are set by a labour union, and are initially flexible, while prices are sticky. the government redistributes using taxes on capital and/or profits.</p>
<p>Only savers choose to save in bonds and capital. The optimality condition for liquid bonds is given by the self-insurance Euler equation: <span class="math display">\[(C_t^S)^{-\frac{1}{\sigma}} = \beta E_t \left\{ \frac{1 + r_t^n}{1 + \pi_{t+1}} \left[ s(C_{t+1}^S)^{-\frac{1}{\sigma}} + (1 - s)(C_{t+1}^H)^{-\frac{1}{\sigma}} \right] \right\}.\]</span> The optimality condition for investment is given by: <span class="math display">\[Q_{t} = \beta E_{t} \left\{ \left( \frac{C_{t+1}^{S}}{C_{t}^{S}} \right)^{-\frac{1}{\sigma}} \left[ (1 - \tau^{K}) R_{t+1}^{K} + Q_{t+1} \left( 1 - \delta + \Phi_{t+1} - \frac{I_{t+1}}{K_{t+1}} \Phi'_{t+1} \right) \right] \right\}.\]</span></p>
<p>Hand-to-mouth households consume their income, which is comprised of labour income and transfers: <span class="math display">\[C_t^H = w_t N_t + T_t^H.\]</span> The government taxes the capital and profit income of the savers, and transfers the revenue to hand-to-mouth households such that the budget balances: <span class="math display">\[\lambda T_t^H = \tau^D + \tau^K r_t^K K_t.\]</span> To turn off the income inequality channel and set <span class="math inline">\(\chi = 1\)</span>, we can implement a perfect redistribution scheme such that: <span class="math display">\[\tau^D = \tau^K = \lambda.\]</span> As all households work the same number of hours and recive the same wage (they are part of the union), this redistribution scheme ensures that incomes are equal.</p>
</section>
<section id="quantifying-the-complementarity" class="level4">
<h4 class="anchored" data-anchor-id="quantifying-the-complementarity">Quantifying the Complementarity</h4>
<p>Table 1 shows the effect of introducing capital on the amplification of monetary policy relative to the RANK model without capital. Firstly, introducing capital to the RANK model serves to dampen the effect of monetary policy, generating an effect only 0.66 times as large as the model without capital. This is because investment is more responsive to output, leading to a smaller consumption response.</p>
<p>Column 3 of <a href="#tbl-1" class="quarto-xref">Table&nbsp;1</a> shows the impact of the capital inequality channel in the TANK model with proportional incomes. As discussed in chapter 3, the TANK model without capital and <span class="math inline">\(\chi = 1\)</span> offers no amplification relative to the RANK model - this is the Campbell-Mankiw benchmark case. Introducing capital amplifies the consumption response by 11%. This demonstrates that, even in the case without income inequality, the capital inequality channel amplifies the effects of monetary policy.</p>
<p>In column 4, we can see the amplification within a THANK model with countercyclical income inequality. Income inequality can lead to substantial amplification, generating a 51% larger consumption response to monetary policy. Importantly, column 4 also shows the strong complementarity between the income and capital inequality channels. When the TANK model features capital and income inequality, the response consumption is 2.25 times alrger than in the baseline RANK model. As discussed above, this joint multiplier is greater than the product of the two individual channels (<span class="math inline">\(2.25 &gt; 1.51 \times 1.11\)</span>).</p>
<p>The final column of <a href="#tbl-1" class="quarto-xref">Table&nbsp;1</a> shows the amplification within a THANK model featuring idiosyncratic risk. Idiosyncratic risk reinforces the complementary between the capital and income inequality channels, leading to a consumption response 2.62 times larger than the RANK case.</p>
<div id="tbl-1" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: Amplification of monetary policy effects on consumption across RANK, TANK and THANK models with and without capital.
</figcaption>
<div aria-describedby="tbl-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th></th>
<th>RANK</th>
<th>Heterogeneous Agents</th>
<th></th>
<th></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td></td>
<td></td>
<td>No Y inequality</td>
<td>Y inequality</td>
<td>+ Risk</td>
</tr>
<tr class="even">
<td>no K</td>
<td>1</td>
<td>1 (=RANK)</td>
<td>1.51</td>
<td>1.60</td>
</tr>
<tr class="odd">
<td>K</td>
<td>0.66</td>
<td>1.11</td>
<td>2.25</td>
<td>2.62</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>We can also use the THANK model with capital to examine the role of fiscal redistribution more closely. As in <a href="#tbl-1" class="quarto-xref">Table&nbsp;1</a>, <a href="#tbl-2" class="quarto-xref">Table&nbsp;2</a> shows that the cases with full redistribution and no redistribution achieve amplification of 11% and 162% respectively.<a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a> However, redistribution of capital and profit income have opposite effects. In the THANK model with capital and only redistribution of profit income, the consumption response to monetary policy is dampened. As profits are countercyclical, increased profit redistribution reduces the cyclicality of hand-to-mouth incomes (a lower value for <span class="math inline">\(\chi\)</span>). Conversely, the case with only redistribution of capital income leads to huge amplification - a consumption response 4.34 times larger than in RANK. As capital income is strongly procyclical, redistribution of capital income makes the income of the hand-to-mouth more procyclical. This makes income inequality more countercyclical, and leads to the amplification of monetary policy. The amplification under capital redistribution is stronger than the dampening under profit redistribution as investment is more cyclical than profits.</p>
<div id="tbl-2" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2: The effects of fiscal redistribution on the amplification of monetary policy in the THANK model with capital.
</figcaption>
<div aria-describedby="tbl-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th>Income Redistribution</th>
<th></th>
<th>Profit Income D</th>
<th></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td></td>
<td></td>
<td>Yes</td>
<td>No</td>
</tr>
<tr class="even">
<td>Capital Income <span class="math inline">\(r^K K\)</span></td>
<td>Yes</td>
<td>1.11</td>
<td>4.34</td>
</tr>
<tr class="odd">
<td></td>
<td>No</td>
<td>0.50</td>
<td>2.62</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>Lastly, <a href="#tbl-3" class="quarto-xref">Table&nbsp;3</a> shows the amplification of monetary policy for the RANK, TANK and THANK models with sticky wages.<a href="#fn5" class="footnote-ref" id="fnref5" role="doc-noteref"><sup>5</sup></a> In the models without capital, we can see that the addition of sticky wages reduces the amplification introduced by the income inequality channel. This is because adding sticky wages removes the countercyclicality of profits - a key mechanism for the amplification of shocks in the TANK and THANK models.</p>
<div id="tbl-3" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;3: Amplification of monetary policy effects on consumption with sticky wages across RANK, TANK and THANK models with and without capital.
</figcaption>
<div aria-describedby="tbl-3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th></th>
<th>RANK</th>
<th>Heterogeneous Agents</th>
<th></th>
<th></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td></td>
<td></td>
<td>No Y inequality</td>
<td>Y inequality</td>
<td>+ Risk</td>
</tr>
<tr class="even">
<td>no K</td>
<td>1</td>
<td>1 (=RANK)</td>
<td>1.01</td>
<td>1.02</td>
</tr>
<tr class="odd">
<td>K</td>
<td>0.94</td>
<td>1.53</td>
<td>1.77</td>
<td>1.95</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>As was the case with sticky prices, capital inequality alone again introduces limited amplification of monetary policy. Comparing the TANK model with capital to the RANK model wit capital shows that capital inequality amplifies monetary policy by approximately 63% (the ratio <span class="math inline">\(1.53 / 0.94\)</span>). This is comparable to the role of capital inequality in the sticky price case (the ratio <span class="math inline">\(1.11 / 0.66\)</span> shows amplification of around 68%).</p>
<p>Importantly, the key result that capital and income inequality are complementary is robust to the model with sticky wages. The amplification with both capital and income inequality is again greater than the product of the indivudal channels (<span class="math inline">\(1.77 &gt; 1.53 \times 1.01\)</span>). The complementary is again reinforced by the addition of idiosyncratic risk, with the THANK model with capital and income inequality generating amplification of 1.95.</p>
</section>
<section id="notes-on-the-literature" class="level4">
<h4 class="anchored" data-anchor-id="notes-on-the-literature">Notes on the Literature</h4>
<p>This chapter is based on Bilbiie et al.&nbsp;(2022). As mentioned in previous chapters, one of the earliest, seminal papers on TANK models focused precisely on physical capital as the asset the holding of which drove the distinction between optimizing agents and “rule of thumb” Galí et al.&nbsp;(2007); that meant that the analysis was a fortiori quantitative, since analytical solutions for models with capital are not easily available. The analysis here provides analytical tools to disentangle the separate roles of income inequality, investment, and MPC heterogeneity. A number of quantitative HANK models also feature capital investment, and therefore implicitly feature the capital inequality channel introduced in this chapter. In the Kaplan et al.&nbsp;(2018) HANK model with liquid and illiquid assets, the response of procyclical investment is a key driver of the consumption response to monetary policy shocks, see also Alves et al.&nbsp;(2020); this is also present in Bayer et al.&nbsp;(2019, 2024); Luetticke (2021); Gornemann et al.&nbsp;(2016); Hagedorn et al.&nbsp;(2019). Auclert et al.&nbsp;(2020) also include investment in an extension of their baseline HANK model, which they estimate—finding that this investment channel is a major contributor to aggregate fluctuations in their model. This model does however abstract from the cyclicality of inequality, meaning that the complementarity between procyclical investment and countercyclical inequality is not a feature of the model.</p>
</section>
<section id="summary" class="level4">
<h4 class="anchored" data-anchor-id="summary">Summary</h4>
<p>In this chapter, we covered an important extension of the THANK model developed in chapters 4 and 5. We showed that physical capital plays an important role in driving the consumption response to monetary policy. In particular, capital and income inequality represent two complementary channels delivering amplification though a ‘multiplier of the multiplier’. Quantitative analysis of the THANK model with capital shows that the redistribution of physical capital and profits have key implications for the strength of monetary policy. These findings yield important insights for both optimal policy design, and for understanding the mechanisms driving the results of the literature on quantitative HANK models featuring capital investment.</p>
</section>
</section>
</section>
<section id="references" class="level1">
<h1>References</h1>
<ul>
<li>Felipe Alves, Greg Kaplan, Benjamin Moll, and Giovanni L. Violante. A Further Look at the Propagation of Monetary Policy Shocks in HANK. Journal of Money, Credit and Banking, 52(S2):521–559, 2020. doi: 10.1111/jmcb.12760.</li>
<li>Adrien Auclert, Matthew Rognlie, and Ludwig Straub. Micro jumps, macro humps: Monetary policy and business cycles in an estimated hank model. Technical report, National Bureau of Economic Research, 2020.</li>
<li>Christian Bayer, Ralph Lütticke, Lien Pham-Dao, and Volker Tjaden. Precautionary Savings, Illiquid Assets, and the Aggregate Consequences of Shocks to Household Income Risk. Econometrica, 87(1):255–290, 2019. doi: 10.3982/ECTA14321.</li>
<li>Christian Bayer, Benjamin Born, and Ralph Luetticke. Shocks, Frictions, and Inequality in US Business Cycles. American Economic Review, 114(5):1211–1247, 2024. doi: 10.1257/aer.20211386. Conditionally accepted.</li>
<li>Florin O Bilbiie, Diego R Känzig, and Paolo Surico. Capital and income inequality: An aggregate-demand complementarity. Journal of Monetary Economics, 126:154–169, 2022. doi: 10.1016/j.jmoneco.2022.01.002.</li>
<li>Olivier Coibion, Yuriy Gorodnichenko, Lorenz Kueng, and John Silvia. Innocent bystanders? monetary policy and inequality. Journal of Monetary Economics, 88:70–89, 2017.</li>
<li>Jordi Galí, J. David López-Salido, and Javier Vallés. Understanding the Effects of Government Spending on Consumption. Journal of the European Economic Association, 5(1):227–270, 2007. doi: 10.1162/JEEA.2007.5.1.227.</li>
<li>Nils Gornemann, Keith Kuester, and Makoto Nakajima. Doves for the Rich, Hawks for the Poor? Distributional Consequences of Monetary Policy. 2016. CEPR Discussion Paper No.&nbsp;DP11233.</li>
<li>Marcus Hagedorn, Iourii Manovskii, and Kurt Mitman. The Fiscal Multiplier. Working Paper 25571, NBER, 2019.</li>
<li>Greg Kaplan, Benjamin Moll, and Giovanni L Violante. Monetary policy according to hank. American Economic Review, 108(3):697–743, 2018. doi: 10.1257/aer.20160042.</li>
<li>Ralph Luetticke. Transmission of Monetary Policy with Heterogeneity in Household Portfolios. American Economic Journal: Macroeconomics, 13(2):1–25, 2021. doi: 10.1257/mac.20190064.</li>
<li>Paul A Samuelson. Interactions between the multiplier analysis and the principle of acceleration. The Review of Economics and statistics, 21(2):75–78, 1939.</li>
</ul>
</section>


<div id="quarto-appendix" class="default"><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Footnotes</h2>

<ol>
<li id="fn1"><p>Based on notes used to teach advanced mini-courses over the last years at the International Monetary Fund, European Central Bank Research Department, Norges Bank, Paris School of Economics (Summer School and APE program), Brown University, HEC Lausanne, Bonn Graduate School of Economics, Goethe University, and Cambridge. I thank Sean Lavender, who provided excellent RA work and help with transcribing the lectures and drafting. TBC<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>In the symmetric steady state, transfers ensure that households have equal consumption such that <span class="math inline">\(C^{S} = C^{H} = C\)</span>.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p>See Appendix B of Bilbiie et al.&nbsp;(2022) for a full description of the model and its loglinearised equilibrium conditions.<a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn4"><p>The case with no redistribution refers to the case with zero taxes. Redistribution still occurs within the model through changes in labour income.<a href="#fnref4" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn5"><p>The model with sticky wages has two sources of nominal rigidities. This creates another break of money neutrality and leads to stronger monetary policy effects. Therefore, the RANK baseline for the sticky wages model features a larger consumption response than in the model with only sticky prices.<a href="#fnref5" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section></div></main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>