## Heterogeneous Agent Macroeconomics

## A Tractable New Keynesian Framework

Florin O. Bilbiie

University of Cambridge & CEPR

Forthcoming, MIT Press

First version 2019, this version November 2025

#### Chapter 8[^1][^2]

Preliminary and Incomplete. Comments Requested

© Florin O. Bilbiie 2019

[^1]: Based on notes used to teach advanced mini-courses over the last years at the International Monetary Fund, European Central Bank Research Department, Norges Bank, Paris School of Economics (Summer School and APE program), Brown University, HEC Lausanne, Bonn Graduate School of Economics, Goethe University, and Cambridge. I thank Sean Lavender, who provided excellent RA work and help with transcribing the lectures and drafting. TBC

[^2]: Partly based on work joint with Xavier Ragot, and Tommaso Monacelli and Roberto Perotti.

# Chapter 8: Optimal Monetary and Fiscal Policy with Inequality: Stabilization and Redistribution

In this section, we will consider optimal fiscal and monetary policy. This will include the welfare criterion and optimal monetary policy in THANK, optimal policy in a liquidity trap, and the optimal mix of fiscal and monetary policy.

In the THANK model we have studied so far, the countercyclicality of income inequality has been the sufficient statistic determining the amplification or dampening of monetary policy. Importantly, the value of $\chi$ is determined by fiscal policy. As in any model with heterogeneous households, the interactions between fiscal and monetary policy will therefore play a crucial role throughout this chapter.

### Optimal Policy in THANK

We will begin by considering optimal policy in the THANK model. The first-best allocation in the model is trivial - the planner would optimally use lump-sum transfers to equalise the marginal utilities of the two types of household. For the world in which the optimal lump-sum transfers are not available, we must consider the Ramsey problem. The primal Ramsey problem sees the planner choose allocations to maximise social welfare subject the the private equilibrium conditions:[^3]
$$\max_{C_t^H, C_t^S, N_t^H, N_t^S, \pi_t} E_0 \sum_{t=0}^{\infty} \beta^t \{ \lambda U(C_t^H, N_t^H) + (1 - \lambda) U(C_t^S, N_t^S) \} + \varsigma_{j,t} \Xi_{j,t}.$$

[^3]: Alternatively, we could take the 'dual' Ramsey approach and choose interest rates directly. The primal and dual approaches will yield the same solution.

Above, $\Xi_{j,t}$ are the Ramsey constraints and $\varsigma_{j,t}$ are the co-state Lagrange multipliers. The Ramsey constraints correspond to the private equilibrium conditions of the model. These can be summarised by:
$$\begin{aligned}
\Xi_{1,t} &= \frac{U_N(N_t^S)}{U_C(C_t^S)} - \frac{U_N(N_t^H)}{U_C(C_t^H)} \\
\Xi_{2,t} &= C_t^H + \frac{U_N(N_t^H)}{U_C(C_t^H)} N_t^H - \frac{\tau^D}{\lambda} \left( 1 - \frac{\psi}{2} \pi_t^2 + \frac{U_N(N_t^H)}{U_C(C_t^H)} \right) (\lambda N_t^H + (1 - \lambda) N_t^S) \\
\Xi_{3,t} &= \lambda C_t^H + (1 - \lambda) C_t^S - \left( 1 - \frac{\psi}{2} \pi_t^2 \right) (\lambda N_t^H + (1 - \lambda) N_t^S) \\
\Xi_{4,t} &= \pi_t (1 + \pi_t) = \beta E_t \left[ \frac{U_C(C_{t+1}^S)}{U_C(C_t^S)} \frac{\lambda N_{t+1}^H + (1 - \lambda) N_t^S}{\lambda N_t^H + (1 - \lambda) N_t^S} \pi_{t+1} (1 + \pi_{t+1}) \right] \\
&\quad + \frac{\varepsilon - 1}{\psi} \left[ \frac{\varepsilon}{\varepsilon - 1} \frac{U_N(N_t^H)}{U_C(C_t^H)} + 1 + \tau^S \right].
\end{aligned}$$

The first constraint represents intratemporal optimality and stipulates that both households earn the same wage. The second constraint corresponds to the budget constraint of the hand-to-mouth household.[^4] The third constraint is the resource constraint. The final constraint is the nonlinear New Keynesian Phillips Curve. In writing these constraints, we have used the production function and the resource constraint to replace aggregate consumption as:
$$C_t = \left(1 - \frac{\psi}{2}\pi_t^2\right)Y_t = \left(1 - \frac{\psi}{2}\pi_t^2\right)N_t.$$ 
We have also used labour market clearing and the profit function to replace profits using:
$$D_{t} = \left(1 - \frac{\psi}{2}\pi_{t}^{2} - W_{t}\right) (\lambda N_{t}^{H} + (1 - \lambda) N_{t}^{S}).$$

[^4]: Walras' law ensures that the savers' budget constraint will also hold.

Importantly, notice that the self-insurance Euler equation is not a constraint in the Ramsey problem. In the THANK model with zero liquidity, the nominal interest rate does not appear in the Ramsey constraints. Once the allocations have been chosen optimally, we can use the Euler equation to determine the nominal interest rate required to implement the optimum residually.[^5]

[^5]: This does not hold in the THANK model with liquidity studied in chapter 5. Here, the nominal interest rate does feature in the budget constraint of the hand to mouth, meaning that the Euler equation must appear as a constraint.

It is simple to show that the Ramsey-optimal steady-state inflation rate is zero. This is the same as in the standard RANK model. Therefore, in our benchmark model, there is no distributional benefit to the central bank targeting a long-run inflation rate above zero.

To find the optimal allocations, we can take the Woodford (2003)-style linear-quadratic approach. Approximating aggregate welfare to second order around the first-best perfect insurance steady state with no income inequality yields the following optimisation problem:
$$\min_{c_t, \pi_t} \frac{1}{2} E_0 \sum_{t=0}^{\infty} \beta^t \left\{ \underbrace{\pi_t^2 + \alpha_y y_t^2}_{RANK} + \underbrace{\alpha_\gamma \gamma_t^2}_{THANK} \right\}$$ {#eq-1}
where $\alpha_y \equiv \frac{\sigma^{-1} + \varphi}{\psi}$ and $\alpha_\gamma \equiv \lambda (1 - \lambda) \sigma^{-1} \varphi^{-1} \alpha_y$,
subject to $\pi_t = \beta E_t \pi_{t+1} + \kappa y_t + u_t$.

We can see that the welfare criterion—first derived in Bilbiie (2008) for TANK and extended to tractable HANK in Bilbiie (2024)—can be expressed as the sum of two parts. The first portion is a quadratic loss function in output and inflation. Importantly, the coefficient on output is the same as in the RANK model. The second term is a quadratic loss function in consumption inequality, $\gamma_t$, which in this model is the same as income inequality. This term is only present in the model with heterogeneous households and measures the deviation from the first-best perfect insurance equilibrium in which there is no consumption or income inequality.[^6] This affects the central bank's stabilization tradeoff, adding a redistribution motive. However, idiosyncratic risk and its cyclicality are irrelevant for optimal policy, insofar as the target flexible-price equilibrium is the first-best with perfect insurance, without inequality; thus, the aggregate implications of the distributional channel for optimal policy in THANK happen to be the same as in TANK.[^7]

[^6]: Other studies found additional stabilization motives using different TANK extensions, e.g. Nistico (2015), Cúrdia and Woodford (2016), and Benigno et al. (2020) for financial-stability motives, Ascari et al. (2017) for wage inflation motives, and Bilbiie and Ragot (2021) for a liquidity-insurance motive with an imperfect-insurance target equilibrium giving rise to a linear term in the approximation.

[^7]: This is the opposite case of the one studied in Challe (2020), which abstracts from inequality altogether; an isomorphism obtains therein too, but between RANK and a different analytical HANK with cyclical risk through search and matching. One common point is that our framework also features risk irrelevance, but in THANK relative to TANK. Both the optimal allocation and the interest rate policy instrument are radically different, and depend crucially on the cyclicality of inequality here. Furthermore, as we will see, in THANK the cyclicality risk does not matter for implementation either.

Recall that in our baseline THANK model, inequality is proportional to aggregate income:
$$\gamma_t = y_t^S - y_t^H = \frac{1 - \chi}{1 - \lambda} y_t.$$ {#eq-2}
This immediately implies an important benchmark result, insofar as this proportionality holds: in the baseline TANK and THANK model, divine coincidence holds. The central bank can stabilize both inflation and output, and in doing so will "for free", also stabilize inequality fluctuations.[^8] As an immediate corollary of this, any monetary rule that mimics optimal policy, which in this model means stabilizing inflation—for instance by a sufficiently aggressive Taylor rule—will also wipe out any equilibrium effect of heterogeneity. This is because the latter manifests itself through the inequality wedge, which is stabilized as a side effect of stabilizing prices, under this "distributional divine coincidence" condition. We will explore some deviations from this below.[^9]

[^8]: This result appeared in a TANK environment already in Bilbiie, but the terminology "divine coincidence" had not been established by the publication date.

[^9]: This feature breaks down generally. Income-inequality proportionality does not hold in analytical models such as Bilbiie et al. (2024) and Acharya et al. (2020), and in quantitative models such as Bhandari et al. (2021) and Bilbiie and Ragot (2021).

For now, working under the assumptions that make @eq-2 hold and substituting it into the welfare criterion @eq-1 we can write the per-period loss function as:
$$\pi_t^2 + \alpha_y \left( 1 + \frac{\lambda}{1 - \lambda} \sigma^{-1} \varphi^{-1} (\chi - 1)^2 \right) y_t^2.$$
This shows that the welfare criterion in the THANK model is the same as in the RANK model, but with a larger coefficient on output volatility. When $\chi \neq 1$, the central bank optimally places more weight on output stabilisation and less weight on inflation stabilisation.[^10] This is because, with heterogeneous households, greater volatility in aggregate output leads to greater volatility in income inequality and a greater departure from the perfect insurance steady state.

[^10]: Risk is also irrelevant for optimal policy in the benchmark THANK model. This is because the probability $s$ only features in the self-insurance Euler equation, which is not a constraint in the optimal policy problem.

Choosing the inflation and output under discretion yields the following targeting rule for the central bank:
$$\pi_t = -\frac{\alpha_y}{\kappa} \left( 1 + \frac{\lambda}{1 - \lambda} \sigma^{-1} \varphi^{-1} (\chi - 1)^2 \right) y_t.$$
Under discretion, optimal policy in the THANK model with cyclical income inequality will result in higher inflation volatility and lower output volatility relative to the RANK model. Note that the sign of the cyclicality of income inequality is irrelevant - it does not matter for optimal policy whether income inequality is procyclical or countercyclical. This is because there is no steady state inequality. A deviation from steady-state output therefore leads to a deviation from optimal steady-state inequality.[^11] As in the RANK model, optimal policy under commitment ultimately amounts to price-level targeting.

[^11]: If the model had positive steady-state inequality, the optimal targeting rule would depend on the sign of the income inequality cyclicality. Suppose that income inequality was countercyclical. In this case, a rise in aggregate income would lead to a fall in income inequality. Starting from the positive-inequality steady state, this rise in income would lead to inequality moving closer to the first-best perfect insurance level. Hence, we would expect the central bank to place less weight on increases in income, leading to asymmetry in the optimal policy rule.

### Optimal Monetary Policy with a Liquidity Motive

In our discussion of optimal policy in the THANK model thus far, we have abstracted from the role of money. In this section, we will review the model developed by Bilbiie and Ragot (2021) in which a liquidity-insurance motive means that the central bank may optimally depart from pursuing price stability.

Consider a THANK model in which money is the only liquid asset. In this case, the loglinearised self-insurance Euler equation is given by:
$$c_t^S = s\beta E_t c_{t+1}^S + (1 - s\beta) E_t c_{t+1}^H + \sigma E_t \pi_{t+1}.$$
Illiquid bonds pay a nominal interest rate but money does not, meaning that the nominal interest rate does not appear in the self-insurance Euler equation. The central bank injects additional money into the economy through helicopter drops.

The source of money demand is idiosyncratic risk and imperfect insurance. Consumption inequality is given by:
$$\gamma_t^c \equiv c_t^S - c_t^H = -\frac{s - (1 - \lambda)}{\lambda} x_t$$
where $x_t$ denotes liquidity. Households engage in precautionary savings using money to self-insure against the risk of becoming hand-to-mouth.

In designing optimal policy, the central bank must balance the benefits from providing liquidity to allow households to self-insure with the costs of inflation. In the flexible price case, the first-best policy is to implement the Friedman rule. Here, the central bank optimally sets $\pi_t = \beta − 1$ to ensure that $i_t = 0$, eliminating the opportunity cost of self-insurance.

In the sticky price case, the key tradeoffs can be seen by examining the budget constraint of the hand-to-mouth households. The budget constraint is given by:
$$c_t^H = Y_t^H + X_t + \frac{1 - s}{\lambda} \frac{M_t}{1 + \pi_t}$$
where $X_t$ denotes money transfers made to H households via helicopter drops, and $M_t$ denotes total money balances saved in the previous period. We can see that helicopter drops increase the liquidity of hand-to-mouth households and provide insurance against becoming constrained. However, the helicopter drops will generally be inflationary. This has two key costs. Firstly, inflation reduces the real value of the money held by the hand-to-mouth households. Secondly, when prices are sticky, inflation forces firms to incur price adjustment costs. The problem of the central bank is to balance the gains from liquidity-insurance against these inflation costs.

To find the optimal policy, we can approximate aggregate utility to second order around a steady state with positive inequality.[^12] The resulting loss function is:
$$\mathcal{L} = \underbrace{\pi_t^2 + \alpha_y c_t^2}_{RANK} + \underbrace{\alpha_\gamma \gamma_t^2}_{\text{ineq. THANK}} - \underbrace{2 \frac{\lambda c^H (\Gamma^{\frac{1}{\sigma}} - 1)}{\psi} c_t^H}_{\text{Novel}}.$$
The first two terms in the loss function are the same as those for the standard THANK model studied in this chapter. The final linear term, which is present due to the long-run inequality, represents the novel liquidity-insurance motive. Helicopter drops increase aggregate welfare directly by increasing the consumption of hand-to-mouth households, providing liquidity and insurance against idiosyncratic risk.

[^12]: Positive steady-state inequality is a requirement for well-defined money demand.

Steady-state inequality is given by:
$$\Gamma = \frac{\frac{1+\pi}{\beta} - s}{1-s} = 1 + \frac{i}{1-s} \ge 1.$$

The liquidity-insurance motive is stronger when steady-state inequality is higher. The motive vanishes in the Friedman rule, which sees long-run inequality approach one.

Due to the presence of the linear term, the linear-quadratic approach cannot be used to solve for optimal policy. Instead, we must solve the full Ramsey problem.

Bilbiie and Ragot (2021) show that the optimal steady-state inflation rate in the model is -0.79%. As we would expect, this inflation rate is higher than that recommended by the Friedman rule (-2%), and lower than the optimal long-run inflation in the RANK model with sticky prices (0%):
$$\text{Friedman Rule} \leq \pi^* \leq 0.$$
The welfare gain associated with moving from 2% annual long-run inflation to the long-run annual inflation implied by $\pi^*$ (-3.2%) is 0.61% of consumption. This figure is broadly consistent with those found by İmrohoroğlu (1992) and Lucas (2000).

[To Be Added: TABLES FROM Bilbiie and Ragot (2021)]

# Stabilisation vs Redistribution: Optimal Fiscal-Monetary Mix

Lastly, we will consider the interactions between fiscal and monetary policy. In models with heterogeneous agents and imperfect insurance, monetary and fiscal policies are inextricably interlinked. When unequal tax incidence leads to fiscal policy having redistributive effects, Bilbiie et al. (2024) show that the 'divine coincidence' is broken.[^13] Fiscal policy leads to inefficient variations in inequality, driving a wedge between the efficient equilibrium and the flexible-price equilibrium. This creates a trade-off for monetary policy between stabilising output and inflation, and offsetting the inefficient fluctuations in inequality. In addition, when fiscal policy can be set optimally, it can be used to counteract the effect of cost-push shocks.

[^13]: In our previous analysis of the THANK model, the divine coincidence remained as income inequality was proportional to aggregate income. In this model, the proportionality will be broken by fiscal transfers.

Consider a variant of the TANK model introduced in chapter 3 with the addition of government spending. Households have separable preferences over private consumption, labour and government spending, $U(C_t^j, N_t^j, G_t^j)$ where:
$$\sigma^{-1} \equiv -\frac{U_{CC}^jC^j}{U_C^j}; \quad \varphi \equiv \frac{U_{NN}^jN^j}{U_N^j}; \quad \sigma_G^{-1} \equiv -\frac{U_{GG}^jG^j}{U_G^j}.$$
In the absence of frictions, government spending optimally satisfies the 'Samuelson rule', equalising the marginal utilities of private consumption and government spending:
$$U_C^j(C) = U_G^j(G).$$
We will adhere to this rule in the frictionless steady state, but will deviate from the benchmark in the short run.

A proportion $\lambda$ of households are hand-to-mouth, consuming all of their income:
$$C_t^H = W_t N_t^H - T_t^H + \frac{\tau^D}{\lambda} D_t.$$
The budget constraint of the $1 - \lambda$ savers is given by:
$$C_t^S + P_t^{-1}B_t^S = P_t^{-1}B_{t-1}^S(1+i_{t-1}) + W_tN_t^S - T_t^S + \frac{1-\tau^D}{1-\lambda}D_t.$$

Households of both types supply labour subject to the intratemporal optimality condition:
$$-U_N^j(N_t^j) = W_t U_C^j(C_t^j).$$
The Euler equation of the savers is:
$$U_C^S(C_t^S) = \beta E_t \left[ \frac{1 + i_t}{\Pi_{t+1}} U_C^S(C_{t+1}^S) \right]$$
where $\Pi_t$ is gross inflation.

Intermediate firms produce using a linear production technology $Y_t(i) = N_t(i)$ and face Rotemberg price adjustment costs. This gives rise to the usual nonlinear Phillips curve:
$$\Pi_t(\Pi_t - 1) = E_t \Lambda_{t,t+1}^S \frac{Y_{t+1}}{Y_t} \Pi_{t+1}(\Pi_{t+1} - 1) + \frac{\theta}{\psi} \left( W_t - (1 + \tau^S) \frac{\theta - 1}{\theta} \right).$$

The aggregate resource constraint requires that output net of adjustment costs must be equal to the sum of private consumption and government spending:
$$Y_t \left[ 1 - \frac{\psi}{2} (\Pi_t - 1)^2 \right] = \lambda C_t^H + (1 - \lambda) C_t^S + G_t.$$

#### Transfers Only

We will first consider the case in which government spending is zero. Fiscal policy therefore consists of pure transfers across household types:
$$G_t = T_t = 0 \rightarrow \lambda T_{H,t} = -(1 - \lambda)T_{S,t}.$$
In loglinearised terms, the transfers to hand-to-mouth agents, and the taxes collected from savers, are given by:[^14]
$$\begin{aligned}
t_{H,t} &\equiv -f_t\\
t_{S,t} &= \frac{\lambda}{1-\lambda} f_t.
\end{aligned}$$

These transfers represent exogenous redistribution, in contrast with the endogenous redistribution encoded in the progressivity of the profit income tax system (which is determined by $\frac{\tau^D}{\lambda}$).

[^14]: Loglinearised taxes are defined in terms of deviations from steady state as a fraction of steady-state output. $t_{j,t} \approx \frac{T_{j,t}-0}{Y}$.

Loglinearising the H budget constraint, and the individual and aggregate intratemporal optimality conditions around the steady state with zero profits and zero inflation gives:
$$\begin{aligned}
c_t^H &= \left(1 - \frac{\tau^D}{\lambda}\right) w_t - t_{H,t}\\
w_t &= \varphi n_t^H + \sigma^{-1} c_t^H\\
w_t &= (\varphi + \sigma^{-1}) c_t.
\end{aligned}$$
Combining these equations allows us to express hand-to-mouth consumption as a function of aggregate consumption and transfers:
$$c_t^H = \chi c_t + z f_t$$
where $\chi \equiv 1 + \varphi \left( 1 - \frac{\tau^D}{\lambda} \right)$; $z \equiv \left[ 1 + (\varphi \sigma)^{-1} \right]^{-1}$.

Using goods market clearing, we can express the consumption of savers as:
$$c_t^S = \frac{1 - \lambda \chi}{1 - \lambda} c_t - \frac{\lambda}{1 - \lambda} z f_t.$$
Income inequality is given by:
$$\gamma_t \equiv c_t^S - c_t^H = \frac{1 - \chi}{1 - \lambda} c_t - \frac{z}{1 - \lambda} f_t.$$
We can see that income inequality is decreasing in transfers. When $\chi > 1$, income inequality is decreasing in aggregate consumption. Importantly, inequality is no longer proportional to aggregate consumption. This will mean that the (distributional) divine coincidence no longer holds in this TANK model.

The savers' loglinearised Euler equation is given by:
$$c_t^S = E_t c_{t+1}^S - \sigma r_t.$$
Substituting the consumption of the savers into the Euler equation yields the aggregate Euler equation:
$$c_t = E_t c_{t+1} - \sigma \frac{1-\lambda}{1-\lambda \chi} (i_t - E_t \pi_{t+1}) + \frac{\lambda}{1-\lambda \chi} z (f_t - E_t f_{t+1}).$$

The aggregate Euler equation illustrates the Monetary-Fiscal Aggregate Demand Equivalence Proposition as stated by Bilbiie et al. (2024). In this TANK model without government spending, transfers can be used as a substitute for monetary policy in aggregate demand management. Choosing a path for transfers or the real interest rate will generate the same aggregate consumption path provided that:
$$\sigma(1-\lambda)(-r_t) = \lambda z(f_t - E_t f_{t+1}).$$

Note that fiscal and monetary policies here have the same aggregate demand effects but different distributional effects. The above equation gives the direct partial equilibrium effect of the policies on aggregate demand. A reduction in the real interest rate causes the $1-\lambda$ savers to substitute consumption from the future into the present. The strength of this channel is governed by $\sigma$, the intertemporal elasticity of substitution. Conversely, fiscal transfers cause the $\lambda$ hand-to-mouth households to increase their present consumption. The strength of this effect is determined by $z$, the elasticity of H consumption to a transfer. In general equilibrium, both of these mechanisms are amplified or dampened through the New Keynesian cross depending on whether income inequality is countercyclical or procyclical.

This aggregate demand equivalence transcends the simple TANK setting. Indeed, Wolf (2021) generalises the proposition to a richer HANK model. In addition, the equivalence has importance for policy in the liquidity trap. If transfers and interest rate cuts are equivalent, fiscal policymakers can stimulate aggregate demand and undo the liquidity trap when the central bank is constrained by the zero lower bound.

In the flexible-price equilibrium, marginal costs are constant. Substituting $w_t^*$ into the aggregate intertemporal optimality equation gives us consumption and inequality in the flexible-price equilibrium:
$$\begin{aligned}
c_t^* &= 0\\
\gamma_t^* &= -\frac{z}{1-\lambda} f_t.
\end{aligned}$$
Under perfect insurance, the equilibrium allocation gives:
$$\begin{aligned}
c_t^{**} &= -\frac{z}{\chi - 1} f_t\\
\gamma_t^{**} &= 0.
\end{aligned}$$
This shows that transfers drive a time-varying wedge between the flexible-price equilibrium and the efficient perfect insurance equilibrium. For $f_t \neq 0$, the divine coincidence is broken.

Recall that the dynamic New Keynesian Phillips Curve in the TANK model is given by:
$$\pi_t = \beta \pi_{t+1} + \kappa c_t$$
where $\kappa \equiv \frac{\theta}{\psi} (\varphi + \sigma^{-1})$.
Under perfect insurance, exogenous transfers of persistence $p$ give rise to inflation equal to:
$$\pi_t^{**} = -\frac{\kappa}{1 - \beta p} \frac{z}{\chi - 1} f_t.$$
When income inequality is countercyclical, positive transfers lead to a deflation and a recession under perfect insurance. From the equation for hand-to-mouth consumption, we can see that transfers have the direct mechanical effect of increasing $c_t^H$ and reducing inequality. The indirect effect of inequality is determined by $\chi$. When $\chi > 1$, the rise in $c_t^H$ must be greater than the rise in aggregate consumption. This means that inequality falls, as shown by the equation for inequality:
$$\gamma_t = \frac{1 - \chi}{1 - \lambda} c_t - \frac{z}{1 - \lambda} f_t.$$

To restore the perfect insurance allocation ($\gamma_t^{**} = 0$), the central bank must induce a recession. This causes aggregate consumption to fall, leading to a rise in inequality when $\chi > 1$. With exogenous transfers, the central bank therefore faces an inherent tension. Monetary policymakers must choose between achieving $\pi_t = 0$ to eliminate price-stickiness distortions on the supply side, and inducing a recession and deflation to stabilise the inequality distortions introduced by fiscal policy on the demand side.

#### Optimal Monetary Policy with Exogenous Transfers

To study optimal policy, Bilbiie et al. (2024) take a second-order expansion of the utility function around the zero-inflation perfect-insurance steady state. As was the case in our standard TANK and THANK model, this yields a quadratic loss function in inflation, the output gap, and inequality. The linear-quadratic policy problem under discretion is therefore to minimise the loss function subject to the Phillips curve (with cost-push shocks) and the equation for income inequality:
$$\begin{aligned}\mathcal{L}_t &\equiv \left\{ \pi_t^2 + \frac{\varphi + \sigma^{-1}}{\psi} c_t^2 + \frac{(\sigma z)^{-1}}{\psi} \lambda (1 - \lambda) \gamma_t^2 \right\}\\
\pi_t& = \beta \pi_{t+1} + \kappa c_t + u_t.
\end{aligned}$$
Once again, the aggregate Euler equation is not a constraint for the monetary policymaker, but is used to determine the nominal interest rate residually.

Substituting the equation for income inequality into the loss function gives:
$$\mathcal{L}_t \equiv \left\{ \pi_t^2 + \frac{\varphi + \sigma^{-1}}{\psi} c_t^2 + \frac{(\sigma z)^{-1}}{\psi} \frac{\lambda (\chi - 1)^2}{1 - \lambda} \left( c_t + \frac{z}{\chi - 1} f_t \right)^2 \right\}.$$
Unlike in our baseline TANK and THANK models, the loss function cannot be expressed purely in terms of variation in inflation and the output gap. The presence of transfers means that the flexible-price output gap is not the welfare-relevant output gap. The final term in the loss function therefore reflects welfare loss due to the output gap deviating from its efficient perfect-insurance level.[^15]

[^15]: Recall that perfect-insurance consumption is given by $c_t^{**} = -\frac{z}{\chi-1}$. The final quadratic term in the loss function can therefore be expressed as $(c_t - c_t^{**})^2$.

Suppose that transfers are set exogenously and have persistence parameter $p$. Assume that the persistence of the cost-push shocks is also given by $p$. Optimal monetary policy under discretion gives the following solution:
$$\begin{aligned}
c_{t} &= -\frac{\lambda}{1 - \lambda} \frac{\chi - 1}{1 + \sigma \varphi} \Phi f_{t} - \frac{\theta}{1 - \beta p} \Phi u_{t}\\
\pi_{t} &= -\frac{\lambda}{1 - \lambda} \frac{\chi - 1}{1 + \sigma \varphi} \frac{\kappa \Phi}{1 - \beta p} f_{t} + \left(1 + \frac{\lambda(\chi - 1)^{2}}{(1 - \lambda)\varphi\sigma}\right) \frac{\Phi}{1 - \beta p} u_{t}\\
\gamma_{t} &= -\frac{z}{1 - \lambda} \left(1 + \frac{\kappa \phi}{1 - \beta p}\right) \Phi f_{t} + \frac{\chi - 1}{1 - \lambda} \frac{\theta}{1 - \beta p} \Phi u_{t}
\end{aligned}$$
where $\Phi \equiv \left[1 + \frac{\kappa \theta}{1 - \beta p} + \frac{\lambda(\chi - 1)^{2}}{(1 - \lambda)\varphi\sigma}\right]^{-1} > 0$.

Even in the absence of cost-push shocks, exogenous transfers mean that it is no longer optimal for the central bank to achieve zero inflation. Instead, when $\chi > 1$, the central bank responds to positive transfers by inducing a deflation and a recession in order to mitigate the distributional gap introduced by the transfers. In the opposite case with $\chi < 1$, the central bank induces inflation and an expansion to counteract the inefficient fall in inequality introduced by the transfers.

### Optimal Fiscal Policy with Exogenous Interest Rates

We can also consider the opposite case in which interest rates are set exogenously and transfers can be chosen optimally. An important difference is that the aggregate Euler equation is now a constraint:[^16]
$$c_t = E_t c_{t+1} - \sigma \frac{1 - \lambda}{1 - \lambda \chi} (i_t^* - E_t \pi_{t+1}) + \frac{\lambda}{1 - \lambda \chi} z (f_t - E_t f_{t+1})$$
where $i_t^*$ is the nominal interest rate set by the central bank.

[^16]: The aggregate Euler must be a constraint as it features the level of transfers, which also appears in the budget constraint of the household.

The solution under optimal policy gives:
$$\begin{aligned}
c_{t} &= -\frac{\sigma(1-\lambda)}{1-p} \Psi i_{t}^{*} - \frac{\lambda \theta \varphi \sigma - p \frac{\sigma}{1-p} (1-\lambda)}{1-\beta p} \Psi u_{t}\\
\text{where } \Psi &\equiv \left[ \lambda \varphi \sigma \left( 1 + \frac{\kappa \theta}{1-\beta p} \right) + (1-\lambda) \left( 1 - p \frac{\sigma}{1-p} \frac{\kappa}{1-\beta p} \right) \right]^{-1}.
\end{aligned}$$
The fiscal reaction function (with $p = 0$) is given by:
$$zf_t = -\frac{\theta\varphi\sigma(1-\lambda\chi)}{(1+\theta\kappa)\varphi\sigma\lambda + 1 - \lambda}u_t + \frac{(1+\theta\kappa)\varphi\sigma + \chi - 1}{(1+\theta\kappa)\varphi\sigma\lambda + 1 - \lambda}\sigma(1-\lambda)i_t^*.$$
As monetary policy is exogenous, transfers must be used for both inflation and inequality stabilisation. A positive cost push shock causes inflation to rise. The fiscal policymaker optimally responds by introducing a tax on hand-to-mouth households. This leads to a recession and a fall in inflation.

# Optimal Policy with Endogenous Transfers: Separation Principles

When one of fiscal or monetary policy is constrained, we have seen that the remaining policy must be used to respond to both stabilisation and redistribution objectives. Now we consider the case in which both policies can be chosen optimally.

In this case, the optimal targeting rule for transfers gives:
$$c_t + \frac{z}{\chi - 1} f_t = 0.$$
This illustrates a key **separation principle**. When monetary and fiscal policy can both be chosen optimally, policymakers should use monetary policy to stabilise the cost-push shock, and fiscal policy should be used to achieve perfect insurance. The separation principle is an example of the classic Tinbergen rule. While heterogeneity introduces another target (distributional considerations), we also have another policy instrument (transfers between household types). The number of instruments is therefore equal to the number of targets, and policymakers can address the stabilisation and redistribution objectives separately.

The equilibrium under optimal policy is the same as in the RANK case, with a cost-push shock leading to a rise in inflation and a fall in output:
$$\begin{aligned}
c_t &= -\frac{\theta}{\theta \kappa + 1 - \beta p} u_t\\
\pi_t &= \frac{1}{\theta \kappa + 1 - \beta p} u_t.
\end{aligned}$$
Optimal transfers are used purely for redistribution:
$$f_t = \frac{\chi - 1}{z} \frac{\theta}{\theta \kappa + 1 - \beta p} u_t.$$
When $\chi > 1$, central bank tightening in response to a cost-push shock causes hand-to-mouth income to fall more than aggregate income. It is therefore optimal to introduce a positive transfer from savers to hand-to-mouth households to reduce inequality towards the perfect-insurance level.

As in the RANK model, the optimal monetary policy instrument rule is independent of distributional terms:
$$i_t = E_t \pi_{t+1} + \frac{\sigma^{-1} z}{\chi - 1} (f_t - E_t f_{t+1}) = \frac{p + \sigma^{-1} \theta (1 - p)}{\theta \kappa + 1 - \beta p} u_t.$$
When transfers can be chosen optimally, monetary policy can be set purely for stabilisation and is independent of distributional considerations.

#### Government Spending

Rather than pure transfers, we can also allow the government to make purchases of consumption goods. Suppose that the government runs a balanced budget and finances spending through lump-sum taxes:
$$G_t = T_t = \lambda T_t^H + (1 - \lambda) T_t^S.$$
To capture the progressivity of the tax system, assume that a share $\alpha$ of total taxes are paid by the $\lambda$ hand-to-mouth households:
$$\lambda T_t^H = \alpha T_t.$$
As in chapter 3, we can loglinearise and decompose the taxes paid by the hand-to-mouth households into two terms:
$$t_{H,t} = \frac{\alpha}{\lambda}t_t = \frac{\alpha}{\lambda}g_t = \underbrace{g_t}_{\text{uniform}} - \underbrace{\left(1 - \frac{\alpha}{\lambda}\right)t_t}_{\text{exogenous redistribution}}$$
If $\alpha < \lambda$, hand-to-mouth households effectively receive a transfer from savers due to the progressivity of the tax system.

The flexible-price allocation in the model with government spending is given by:
$$\begin{aligned}
c_t^* &= -\tilde{z}\tilde{g}_t\\
\text{where } \tilde{z} &\equiv \left[1 + (\tilde{\varphi}\sigma)^{-1}\right]^{-1}\\
\tilde{g}_t &\equiv \frac{1}{1 - G_Y} g_t\\
\tilde{\varphi} &\equiv \varphi(1 - G_Y).
\end{aligned}$$

The loglinearised consumption of hand-to-mouth households can be expressed as:
$$c_t^H = \chi c_t - \tilde{z}t_{H,t} = \chi c_t + \tilde{z}\left(\chi - \frac{\alpha}{\lambda}\right)\tilde{g}_t.$$
The aggregate Euler equation is given by:
$$c_t = E_t c_{t+1} + \frac{\lambda}{1 - \lambda \chi} \tilde{z} \left( \chi - \frac{\alpha}{\lambda} \right) (\tilde{g}_t - E_t \tilde{g}_{t+1}) - \sigma \frac{1 - \lambda}{1 - \lambda \chi} (i_t - E_t \pi_{t+1}).$$
As was the case in the model with pure transfers, this yields a **Monetary-Fiscal Aggregate Demand Equivalence Proposition**. Real interest rate cuts and changes in government spending have the same aggregate demand effect provided that:
$$\sigma(1-\lambda)(-r_t) = \lambda \tilde{z} \left(\chi - \frac{\alpha}{\lambda}\right) (\tilde{g}_t - E_t \tilde{g}_{t+1}).$$
A key difference with the pure transfers case is that the effects of government spending depend on the cyclicality of income inequality compared to the degree of progressivity embedded in the tax system. Importantly, if $\chi = \frac{\alpha}{\lambda}$, then there can be no equivalence between fiscal and monetary policy.[^17]

[^17]: A second caveat is that the above proposition is for a fixed real interest rate. Government spending also has supply effects, as shown by the Phillips curve, $\pi_t = \beta E_t \pi_{t+1} + \kappa (c_t + \tilde{z}\tilde{g}_t)$.

# Optimal Monetary Policy with Exogenous Government Spending

When government spending is set exogenously with persistence $p$, the solution under optimal monetary policy is given by:
$$\begin{aligned}
c_{t} + \tilde{z}\tilde{g}_{t} &= -\left(1 - \frac{\alpha}{\lambda}\right)(\chi - 1)\frac{\lambda}{1 - \lambda}\frac{\tilde{\Phi}}{1 + \sigma\tilde{\varphi}}\tilde{g}_{t}\\
\pi_{t} &= \frac{\kappa\tilde{\Phi}}{1 - \beta p}(c_{t} + \tilde{z}\tilde{g}_{t})\\
\gamma_{t} &= -\left(1 - \frac{\alpha}{\lambda}\right)\left(1 + \frac{\kappa\theta}{1 - \beta p}\right)\frac{\tilde{z}\tilde{\Phi}}{1 - \lambda}\tilde{g}_{t}.
\end{aligned}$$

The term $\left(1 - \frac{\alpha}{\lambda}\right)(\chi - 1)$ is the key statistic governing exogenous and endogenous redistribution. Suppose that the government spending is financed by progressive taxation $\alpha < \lambda$. In this case, a rise in government spending directly results in a rise in the income of the hand-to-mouth and an inefficient reduction in inequality. When $\chi > 1$, inequality falls further below the perfect-insurance benchmark ($\gamma_t^{**} = 0$) as hand-to-mouth income rises by more than aggregate income. The central bank optimally responds by inducing a negative output gap relative to the flexible-price output level ($c_t + \tilde{z}\tilde{g}_t < 0$) and a deflation. Even in the case without cost-push shocks, the presence of exogenous government spending means that the central bank does not optimally stabilise inflation. This is because government spending with unequal tax incidence works as a 'cost-pull shock', which causes the flexible-price output to be larger than perfect-insurance output. The central bank faces the stabilisation-redistribution trade-off must optimally induce a deflation to mitigate the distributional gap introduced by the government spending and progressive taxation.

# Optimal Monetary and Fiscal Policy with Endogenous Government Spending

Consider the case in which the government can set both fiscal and monetary policy optimally. In this case, the first-order conditions of the optimal policy problem yield:
$$\tilde{g}_t = -\left(1 - \frac{\alpha}{\lambda}\right) (\chi - 1) \frac{\lambda}{1 - \lambda} \frac{\tilde{\sigma}_G}{\tilde{z}\tilde{\sigma}_G + \sigma} \left(c_t + \frac{\chi - \frac{\alpha}{\lambda}}{\chi - 1}\tilde{z}\tilde{g}_t\right).$$
Consumption under perfect insurance ($\gamma_t^{**}$) is equal to:
$$c_t^{**} = c_t^* + \frac{1 - \frac{\alpha}{\lambda}}{1 - \chi} \tilde{z} \tilde{g}_t = -\frac{\chi - \frac{\alpha}{\lambda}}{\chi - 1} \tilde{z} \tilde{g}_t.$$
The first-order conditions therefore show that optimal government spending is proportional to the output gap compared to the perfect-insurance solution, with the sign determined by $\left(1-\frac{\alpha}{\lambda}\right)(\chi-1)$.

With uniform incidence, we have another separation principle:
$$\begin{aligned}
\tilde{g}_t &= 0 \\
\kappa \pi_t + \frac{\sigma^{-1} + \tilde{\varphi}}{\psi} c_t &= 0.
\end{aligned}$$\

Given incidence $\alpha$ and an AR(1) process for shocks, the solution under optimal policy is given by:
$$\begin{aligned}
\tilde{g}_t^{opt} &= \left(1 - \frac{\alpha}{\lambda}\right) (\chi - 1) \Psi u_t, \quad \Psi > 0 \\
c_t &= -\left[\frac{1 - \lambda}{\lambda} (\tilde{z} + \sigma \tilde{\sigma}_G^{-1}) + \tilde{z} \left(1 - \frac{\alpha}{\lambda}\right) \left(\chi - \frac{\alpha}{\lambda}\right)\right] \Psi u_t \\
\gamma_t &= \frac{\chi - 1}{\lambda} (\tilde{z} + \sigma \tilde{\sigma}_G^{-1}) \Psi u_t.
\end{aligned}$$

When tax incidence is unequal across household types, government spending is optimally used to stabilise cost-push shocks. In the case with progressive taxation ($\alpha < \lambda$) and countercyclical income inequality ($\chi > 1$), optimal government spending is countercyclical. A positive cost-push shock causes a rise in inflation and a fall in output. As $\chi > 1$, the recession leads to a rise in inequality. A rise in government spending can counteract these effects. The transfers embedded in the progressive tax system help to close the inequality gap, while the New Keynesian cross amplification of the government spending reduces the output gap. In New Keynesian terminology, the 'cost-pull' government spending increase can be used to mitigate the cost-push shock.

When taxation is regressive ($\alpha > \lambda$), government spending leads to a rise in inequality and output. In this case, optimal government spending in response to a cost-push shock must be procyclical.

#### Notes on the Literature

This chapter is based on topics covered in a growing literature on optimal monetary and fiscal policy in HANK models, and on the literature on optimal policy in TANK models that preceded it. Two extensions of the TANK optimal-policy analysis in Bilbiie (2008) are particularly worth emphasizing: to sticky wages (Ascari et al. (2017)) and to transition between the two states but with a different asset market structure compared to THANK, giving rise to a financial stability motive (Nistico (2015)).

In a quantitative HANK model, Bhandari et al. (2021) show that the Ramsey planner faces a strong insurance motive, and chooses a higher level of inflation volatility relative to the RANK model; see also Nuño and Thomas (2022) for another pioneering contribution to solving optimal policy in full HANK models. Acharya et al. (2020) use an analytical HANK model to show that the planner optimally seeks to reduce consumption dispersion across households, echoing previous results in Bilbiie (2008, 2024) in a different tractable environment. Furthermore, with countercyclical income risk, the planner optimally responds to negative productivity shocks by choosing a lower path of interest rates than in the RANK model. This policy response keeps output higher, reducing income risk and the average MPC. Hence, consumption dispersion is reduced at the cost of output and inflation rising above their efficient levels.

McKay and Wolf (2023) also study optimal policy rules in HANK models. While the results do show that the Ramsey planner's objective is adapted to include a consumption inequality term, the optimal interest rate choice is little affected by this modification. Instead, the authors show that fiscal transfers are a more effective policy instrument for reducing consumption inequality, as was the case in the separation principles derived for the THANK model discussed in this chapter; see also Dávila and Schaab (2023). The separation principles are also similar to the optimal policy conclusions drawn by Le Grand et al. (2021). In a HANK model with optimal capital and labour taxes, the authors show that it is optimal for the monetary authority to stabilise prices rather than fluctuations in inequality.

## Summary

In this chapter, we have analysed optimal fiscal and monetary policy in TANK and THANK models. We have shown that the inclusion of heterogeneous households can have important implications for the design of optimal policy.

In our baseline THANK model, cyclical inequality gives rise to greater inflation volatility and lower output volatility as the central bank seeks to minimise deviations from the first-best perfect-insurance allocation. Introducing steady-state inequality and money into the model creates an additional liquidity-insurance motive for monetary policymakers.

Lastly, we showed that the interactions between monetary and fiscal policy are crucial in models with heterogeneous agents. Exogenous transfers between household types or government spending financed with unequal tax incidence create inefficient fluctuations in inequality, presenting a stabilisation-redistribution tradeoff for policymakers. When government spending can be chosen optimally to counteract cost-push shocks, the optimal cyclicality of spending is determined by the degree of redistribution embedded in the tax system and in the cyclicality of income inequality.

# References

- Sushant Acharya, Edouard Challe, and Keshav Dogra. Optimal monetary policy according to hank. 2020.
- Guido Ascari, Andrea Colciago, and Lorenza Rossi. Limited Asset Market Participation and Optimal Monetary Policy. Economic Inquiry, 2017. doi: 10.1111/ecin.12413.
- Pierpaolo Benigno, Gauti Eggertsson, and Francesco Romei. Dynamic debt deleveraging and optimal monetary policy. American Economic Journal: Macroeconomics, 12(4):310–350, 2020.
- Anmol Bhandari, David Evans, Mikhail Golosov, and Thomas J Sargent. Inequality, business cycles, and monetary-fiscal policy. Econometrica, 89(6):2559–2599, 2021. doi: 10.3982/ECTA17066.
- Florin O. Bilbiie. Limited Asset Markets Participation, Monetary Policy and (Inverted) Aggregate Demand Logic. Journal of Economic Theory, 140(1):162–196, 2008. doi: 10.1016/j.jet.2007.06.010.
- Florin O. Bilbiie. Monetary policy and heterogeneity: An analytical framework. Review of Economic Studies, 2024.
- Florin O Bilbiie and Xavier Ragot. Optimal monetary policy and liquidity with heterogeneous households. Review of Economic Dynamics, 41:71–95, 2021.
- Florin O. Bilbiie, Tommaso Monacelli, and Roberto Perotti. Stabilization vs. redistribution: The optimal monetary-fiscal mix. Technical report, August 2024. Available at CEPR.
- Edouard Challe. Uninsured unemployment risk and optimal monetary policy in a zero-liquidity economy. American Economic Journal: Macroeconomics, 12(1):241–283, 2020.
- Vasco Cúrdia and Michael Woodford. Credit Frictions and Optimal Monetary Policy. Journal of Monetary Economics, 84:30–65, 2016. doi: 10.1016/j.jmoneco.2015.12.002.
- Eduardo Dávila and Andreas Schaab. Optimal monetary policy with heterogeneous agents: Discretion, commitment, and timeless policy. Working Paper 2023/18, Federal Reserve Bank of New York, 2023.
- Ayşe İmrohoroğlu. The welfare cost of inflation under imperfect insurance. Journal of Economic Dynamics and Control, 16(1):79–91, 1992.
- François Le Grand, Alaïs Martin-Baillon, and Xavier Ragot. Should Monetary Policy Care about Redistribution? Optimal Fiscal and Monetary Policy with Heterogeneous Agents. 2021. Sciences Po Working Paper.
- Robert E Lucas, Jr. Inflation and welfare. Econometrica, 68(2):247–274, 2000.
- Alisdair McKay and Christian K. Wolf. Optimal policy rules in HANK. Working Paper 31050, National Bureau of Economic Research (NBER), 2023.
- Salvatore Nistico. Optimal monetary policy and financial stability in a non-ricardian economy. Journal of the European Economic Association, 13(6):1332–1366, 2015.
- Galo Nuño and Carlos Thomas. Optimal redistributive inflation. Annales d'Economie et de Statistique, 147:119–150, 2022.
- Christian K Wolf. Interest rate cuts vs. stimulus payments: An equivalence result. Technical report, National Bureau of Economic Research, 2021.
- Michael Woodford. Interest and prices: Foundations of a theory of monetary policy, 2003.
