## Heterogeneous Agent Macroeconomics

## A Tractable New Keynesian Perspective

Florin O. Bilbiie

University of Cambridge & CEPR

Forthcoming, MIT Press

First version 2019, this version November 2025

#### Chapter 6[^1]

Preliminary and Incomplete. Comments Requested

© Florin O. Bilbiie 2019

[^1]: Based on notes used to teach advanced mini-courses over the last years at the International Monetary Fund, European Central Bank Research Department, Norges Bank, Paris School of Economics (Summer School and APE program), Brown University, HEC Lausanne, Bonn Graduate School of Economics, Goethe University, and Cambridge. I thank Sean Lavender, who provided excellent RA work and help with transcribing the lectures and drafting. TBC

[^2]: Based on work joint with Diego Känzig and Paolo Surico.

# Chapter 6: Illiquidity, Unequal Saving, and Physical Capital Investment: Multiplier-Accelerator Redux

In this chapter, we consider an important extension of the THANK model developed in chapters 4 and 5. We add investment in physical capital to the model, and show the complementarity between income and wealth inequality in generating aggregate-demand amplification.

In our THANK model studied so far, and indeed in the textbook treatment of the RANK model, we have abstracted from physical capital. Nevertheless, capital plays a central role in macroeconomics and the study of business cycles. For instance, a key feature of Real Business Cycle models is that capital investment is approximately 4 times as volatile as GDP.

However, the recent growth of the HANK literature has prompted a reappraisal of the role of capital in New Keynesian models. In the model developed by Bilbiie et al. (2022), we will see that heterogeneity moves capital to the forefront in determining the consumption response to monetary policy shocks. Crucially, the model isolates two amplification channels for monetary policy. The first channel is the cyclical income inequality channel - the focus of our THANK model analysis thus far. The addition of capital leads to a second capital inequality channel, which resuscitates the Samuelson (1939) multiplier-accelerator. We will see that these channels are complementary in amplifying monetary policy in the model, with the joint effects of capital and income inequality exceeding the individual effects combined.

#### A Tale of Two Inequalities

To examine the complementarity between capital and income inequality, we will first consider a simple heterogeneous-agent model. In this framework, the budget constraint of household j is given by:
$$C^{j} + S^{j} = (WN)^{j} + (rK + D)^{j} + T^{j} \equiv Y^{j}.$$
Above, $C^{j}$ denotes the consumption of household j, while $S^j$ represents the household's savings. Household savings are in physical capital, which is denoted by $K$. The household earns labour income $(W N)^{j}$ as well as financial income from the return on capital $rK$ and dividends $D$.

The budget constraint highlights the two sources of inequality in the model. Firstly, in the THANK model without capital, the budget constraint would be given by:
$$C^j = (WN)^j + D^j + T^j \equiv Y^j.$$
Here, households differ in their consumption expenditures and their income. This income inequality was the key focus of our analysis of the THANK model. Conversely, in the model with capital, households also have heterogeneous savings capital inequality. To isolate the capital inequality channel, we can assume that transfers ensure that incomes are equal across households. This gives the following budget constraint:
$$C^j + S^j = Y.$$

#### A Simple Heterogeneous-Agent Model with Capital

As in the THANK model, consider an economy populated by two types of household. A share $\lambda$ of the households are hand-to-mouth (H), who consume all of their income. The remaining share $1 - \lambda$ are savers (S), who consume and save in physical capital. Loglinearising the model around the symmetric steady state yields the Euler equation:[^3]
$$c_t^S = E_t c_{t+1}^S - r_t.$$
Loglinearising the household budget constraints gives:
$$\begin{aligned}
C_Y c_t^S + \frac{I_Y}{1 - \lambda} i_t &= Y_Y^S y_t^S\\
c_t^H &= y_t^H = \chi y_t
\end{aligned}$$
where $i_t$ denotes investment and $\chi$ is the elasticity of hand-to-mouth income to aggregate income. $X_Y$ denotes the steady state of a variable as a share of steadystate output.

[^3]: In the symmetric steady state, transfers ensure that households have equal consumption such that $C^{S} = C^{H} = C$.

For simplicity, we will initially assume that households follow an exogenous isoelastic investment function:
$$i_t = \eta y_t.$$
Aggregate consumption and investment and given by:
$$\begin{aligned}
c_t &= \lambda c_t^H + (1 - \lambda)c_t^S\\
y_t &= \lambda Y_Y^H y_t^H + (1 - \lambda)Y_Y^S y_t^S.
\end{aligned}$$
Goods market clearing requires that:
$$y_t = C_Y c_t + I_Y i_t.$$

To isolate the role of capital inequality, consider the case with $\chi = 1$ such that the income inequality channel offers no amplification of monetary policy. An implication of this case is that households' incomes are proportional, meaning that $y_t = y_t^S = y_t^H$. From the equation for aggregate consumption, we can express the consumption of savers as:
$$c_t^S = \frac{c_t - \lambda c_t^H}{1 - \lambda} = \frac{c_t - \lambda y_t}{1 - \lambda}.$$
From the goods market clearing condition, we have:
$$c_t = \frac{y_t - I_Y i_t}{C_Y}.$$
The steady-state goods market cleaaring condition gives us:
$$C_Y + I_Y = 1.$$
We can therefore use the investment function to express aggregate consumption as:
$$c_t = \frac{1 - \eta I_Y}{1 - I_Y} y_t.$$

Substituting these equations into the savers' Euler equation yields the aggregate Euler equation:
$$c_t = E_t c_{t+1} - \underbrace{\frac{1 - \lambda}{1 - \lambda \frac{1 - I_Y}{1 - \eta I_Y}}}_{\text{Multiplier}} r_t.$$
In this model, we can see that the consumption response to a one-time real interest rate change is given by:
$$\left| \frac{\partial c_t}{\partial r_t} \right|_{K\text{ inequality}} = \frac{1 - \lambda}{1 - \lambda \frac{1 - I_Y}{1 - \eta I_Y}}.$$
Recall that the aggregate Euler equation for the RANK model featured a unit coefficient on the real interest rate. The introduction of capital therefore introduces another Keynesian-cross multiplier and amplifies the effect of monetary policy if and only if $\eta > 1$. This condition requires that investment is procyclical and more volatile in output. Hence, well documented business cycle statistics show that the condition will be satisfied in reality.

The multiplier is present because the investment of the savers generates income which is partly received by hand-to-mouth households. When savers invest, aggregate income rises due to the increase in capital income. A portion of this rise in income will accrue to hand-to-mouth households. This redistribution could take place directly through the tax system, or indirectly through a rise in labour demand leading to increased labour income for H households. The rise in income causes H households to increase their consumption, leading to a further rise in income. Savers invest a proportion $\eta$ of this rise in income, causing a further round of income increases. This leads to a Keynesian-cross multiplier summarised by the term $\frac{1-I_Y}{1-\eta I_Y}$, and essentially follows the logic of the Samuelson (1939) multiplier-accelerator.

### Aggregate Demand Complementarity: 'The Multiplier of the Multiplier'

In the above section, we have shown that the inclusion of capital inequality amplifies the consumption effects of monetary policy, even in the case with proportional incomes. Reintroducing countercyclical income inequality gives a multiplier of:
$$\left|\frac{\partial c_t}{\partial r_t}\right|_{K \& Y\text{ inequality}} = \frac{1-\lambda}{1-\lambda\chi\frac{1-I_Y}{1-\eta I_Y}}.$$

Importantly, provided that investment is sufficiently procyclical $(\eta > 1)$ and hand-tom-mouth income is more volatile than aggregate income $(\chi)$, we can see that income and capital inequality interact to generate amplification which is greater than the two inequality channels combined. To see this complementarity, recall that the multiplier for the model with only income inequality is:
$$\left| \frac{\partial c_t}{\partial r_t} \right|_{Y\text{ inequality}} = \frac{1 - \lambda}{1 - \lambda \chi}.$$
We can therefore see that:
$$\begin{aligned}
\left| \frac{\partial c_t}{\partial r_t} \right|_{K \& Y\text{ inequality}} &> \left| \frac{\partial c_t}{\partial r_t} \right|_{K\text{ inequality}} \times \left| \frac{\partial c_t}{\partial r_t} \right|_{Y\text{ inequality}} \\
\frac{1-\lambda}{1-\lambda\chi\frac{1-I_Y}{1-\eta I_Y}} &> \frac{1-\lambda}{1-\lambda\frac{1-I_Y}{1-\eta I_Y}} \times \frac{1-\lambda}{1-\lambda\chi}
\end{aligned}$$
if $\eta > 1$ and $\chi > 1$. Capital inequality serves to amplify the effects of income inequality, serving as a 'multiplier of the multiplier'. Recall that the numerator of the multiplier represents the 'direct effect' of the interest rate change, with a mass $1 - \lambda$ of savers increasing consumption due to intertemporal substitution following an interest rate cut. The denominator represents the indirect effects of interest rate changes. Therefore, the multiplier for the model with both capital and income inequality shows that the indirect effects interact nonlinearly in each round, and act as multipliers of each other.

When savers invest, aggregate income rises. When $\chi > 1$, the income of the hand-to-mouth households rises more than one-for-one with aggregate income. This leads to a rise in H households' consumption demand and a further rise in aggregate income. When $\eta > 1$, the savers respond to this rise in aggregate income by increasing investment further, beginning another round of consumption increases.

#### Simple Testable Predictions

This simple TANK model with capital inequality yields two testable predictions. Firstly, we can express income and consumption inequality as:
$$\begin{aligned}
y_t^S - y_t^H &= \frac{1 - \chi}{(1 - \lambda)Y_Y^S} y_t\\
c_t^S - c_t^H &= \frac{1 - \chi C_Y - \eta I_Y}{(1 - \lambda)C_Y} y_t.
\end{aligned}$$
Income inequality is countercyclical when $\chi > 1$. Consumption inequality is countercyclical if and only if:
$$C_Y(\chi - 1) + I_Y(\eta - 1) > 0.$$
This means that, given that investment is more than one-to-one procyclical, consumption inequality can be countercyclical even in the case where income inequality is not.

Secondly, consumption inequality is more countercyclical than income inequality if $\eta > 1$. This theoretical prediction is consistent with recent empirical studies. For instance, Coibion et al. (2017) use US consumer survey data to show that expenditure inequality rises more than income inequality following a contractionary monetary policy shock. This suggests that consumption inequality is indeed more countercyclical than income inequality.

#### Policy Implications: Determinacy and Forward Guidance

We can also amend our simple model to consider the implications of capital inequality for determinacy and forward guidance. Suppose now, as in the THANK model, that households face idiosyncratic income risk, with savers becoming handto-mouth next period with probability $1 - s$. The self-insurance Euler equation in this case is:
$$c_t^S = sE_t c_{t+1}^S + (1-s)E_t c_{t+1}^H - r_t.$$
This simple THANK model yields and aggregate Euler equation:

$$\begin{aligned}
c_t &= \Theta E_t c_{t+1} - \Omega r_t\\
\text{where } \Theta &\equiv 1 + (1 - s) \frac{\chi \frac{1 - I_Y}{1 - \eta I_Y} - 1}{1 - \lambda \chi \frac{1 - I_Y}{1 - \eta I_Y}}\\
\text{and } \Omega &\equiv \frac{1 - \lambda}{1 - \lambda \chi \frac{1 - I_Y}{1 - \eta I_Y}}.
\end{aligned}$$

In order for the model to generate compounding of news shocks, the coefficient on expected consumption must be greater than one. This requires that:
$$\begin{aligned}
\chi \frac{1 - I_Y}{1 - \eta I_Y} &> 1\\
\Rightarrow \eta &> 1 + (1 - \chi) \frac{1 - I_Y}{I_Y}.
\end{aligned}$$
When investment is sufficiently procyclical, the model with capital inequality will generate compounding. With procyclical investment, a 'good news shock' about future aggregate output will lead to a larger rise in future investment. This investment will lead to a rise in future aggregate income, and a rise in the future income of the hand-to-mouth households. As a result, the precautionary saving motive is weakened and households increase present consumption by more in response to the expected future shock.

As was the case in the THANK model with only income inequality, the compounding of news shocks has important implications for the forward guidance puzzle and the requirements for determinacy under an interest rate rule.

The present consumption response to an announced interest rate cut in period $t + T$ is given by:
$$\frac{\partial c_t}{\partial (-r_{t+T})} = \Theta^T \Omega.$$
When investment is sufficiently procyclical such that $\Omega > 1$, the consumption response to the interest rate cut will be increasing in its horizon. Introducing capital inequality therefore means that the forward guidance puzzle can persist even in the case with acyclical or procyclical income inequality. Hence, the result that procyclical income inequality solves the forward guidance puzzle does not necessarily generalise to our setting with both income and capital inequality.

To analyse the implications of capital inequality for determinacy, suppose that the central bank sets nominal interest rates according to a Taylor rule, and introduce a simple static Phillips curve:
$$\begin{aligned}
r_t^n \equiv r_t + E_t \pi_{t+1} &= \phi_\pi \pi_t\\
\pi_t &= \kappa c_t.
\end{aligned}$$
Substitute these equilibrium conditions into the aggregate Euler equation to obtain:
$$c_t = \frac{\Theta + \kappa \Omega}{1 + \phi_\pi \kappa \Omega} E_t c_{t+1}.$$
For determinacy under a Taylor rule, the coefficient on expected consumption must be less than one. This gives the following condition on $\phi_\pi$:
$$\phi_{\pi} > 1 + \frac{\Theta - 1}{\kappa \Omega}.$$

The condition for determinacy therefore becomes more stringent than the Taylor principle ($\phi_\pi > 1$) when investment is sufficiently procyclical such that $\Theta > 1$. The capital inequality channel weakens the endogenous dampening from precautionary saving and idiosyncratic risk, and leads to compounding of news shocks. The central bank must therefore respond more strongly to rises in inflation in order to prevent sunspots from becoming self fulfilling.

#### A Tractable HANK with Capital

To quantify the effects of and complementarity between capital and income inequality channels, Bilbiie et al. (2022) develop a THANK model with illiquid capital.[^4] As in the THANK model with only income inequality, households face idiosyncratic risk such that the stationary share of hand-to-mouth households is again given by:
$$ \lambda = \frac{1-s}{2-s-h}. $$

[^4]: See Appendix B of Bilbiie et al. (2022) for a full description of the model and its loglinearised equilibrium conditions.

Households can save in liquid bonds, illiquid shares, or illiquid capital. The evolution of capital is given by:
$$K_{t+1} = (1 - \delta)K_t + \Phi\left(\frac{I_t}{K_t}\right)K_t$$
where the function $\Phi()$ represents capital adjustment costs. Wages are set by a labour union, and are initially flexible, while prices are sticky. the government redistributes using taxes on capital and/or profits.

Only savers choose to save in bonds and capital. The optimality condition for liquid bonds is given by the self-insurance Euler equation:
$$(C_t^S)^{-\frac{1}{\sigma}} = \beta E_t \left\{ \frac{1 + r_t^n}{1 + \pi_{t+1}} \left[ s(C_{t+1}^S)^{-\frac{1}{\sigma}} + (1 - s)(C_{t+1}^H)^{-\frac{1}{\sigma}} \right] \right\}.$$
The optimality condition for investment is given by:
$$Q_{t} = \beta E_{t} \left\{ \left( \frac{C_{t+1}^{S}}{C_{t}^{S}} \right)^{-\frac{1}{\sigma}} \left[ (1 - \tau^{K}) R_{t+1}^{K} + Q_{t+1} \left( 1 - \delta + \Phi_{t+1} - \frac{I_{t+1}}{K_{t+1}} \Phi'_{t+1} \right) \right] \right\}.$$

Hand-to-mouth households consume their income, which is comprised of labour income and transfers:
$$C_t^H = w_t N_t + T_t^H.$$
The government taxes the capital and profit income of the savers, and transfers the revenue to hand-to-mouth households such that the budget balances:
$$\lambda T_t^H = \tau^D + \tau^K r_t^K K_t.$$
To turn off the income inequality channel and set $\chi = 1$, we can implement a perfect redistribution scheme such that:
$$\tau^D = \tau^K = \lambda.$$
As all households work the same number of hours and recive the same wage (they are part of the union), this redistribution scheme ensures that incomes are equal.

#### Quantifying the Complementarity

Table 1 shows the effect of introducing capital on the amplification of monetary policy relative to the RANK model without capital. Firstly, introducing capital to the RANK model serves to dampen the effect of monetary policy, generating an effect only 0.66 times as large as the model without capital. This is because investment is more responsive to output, leading to a smaller consumption response.

Column 3 of @tbl-1 shows the impact of the capital inequality channel in the TANK model with proportional incomes. As discussed in chapter 3, the TANK model without capital and $\chi = 1$ offers no amplification relative to the RANK model - this is the Campbell-Mankiw benchmark case. Introducing capital amplifies the consumption response by 11%. This demonstrates that, even in the case without income inequality, the capital inequality channel amplifies the effects of monetary policy.

In column 4, we can see the amplification within a THANK model with countercyclical income inequality. Income inequality can lead to substantial amplification, generating a 51% larger consumption response to monetary policy. Importantly, column 4 also shows the strong complementarity between the income and capital inequality channels. When the TANK model features capital and income inequality, the response consumption is 2.25 times alrger than in the baseline RANK model. As discussed above, this joint multiplier is greater than the product of the two individual channels ($2.25 > 1.51 \times 1.11$).

The final column of @tbl-1 shows the amplification within a THANK model featuring idiosyncratic risk. Idiosyncratic risk reinforces the complementary between the capital and income inequality channels, leading to a consumption response 2.62 times larger than the RANK case.

| | RANK | Heterogeneous Agents | | |
|---|---|---|---|---|
| | | No Y inequality | Y inequality | + Risk |
| no K | 1 | 1 (=RANK) | 1.51 | 1.60 |
| K | 0.66 | 1.11 | 2.25 | 2.62 |

: Amplification of monetary policy effects on consumption across RANK, TANK and THANK models with and without capital. {#tbl-1}

We can also use the THANK model with capital to examine the role of fiscal redistribution more closely. As in @tbl-1, @tbl-2 shows that the cases with full redistribution and no redistribution achieve amplification of 11% and 162% respectively.[^5] However, redistribution of capital and profit income have opposite effects. In the THANK model with capital and only redistribution of profit income, the consumption response to monetary policy is dampened. As profits are countercyclical, increased profit redistribution reduces the cyclicality of hand-to-mouth incomes (a lower value for $\chi$). Conversely, the case with only redistribution of capital income leads to huge amplification - a consumption response 4.34 times larger than in RANK. As capital income is strongly procyclical, redistribution of capital income makes the income of the hand-to-mouth more procyclical. This makes income inequality more countercyclical, and leads to the amplification of monetary policy. The amplification under capital redistribution is stronger than the dampening under profit redistribution as investment is more cyclical than profits.

[^5]: The case with no redistribution refers to the case with zero taxes. Redistribution still occurs within the model through changes in labour income.

| Income Redistribution | | Profit Income D | |
|---|---|---|---|
| | | Yes | No |
| Capital Income $r^K K$ | Yes | 1.11 | 4.34 |
| | No | 0.50 | 2.62 |

: The effects of fiscal redistribution on the amplification of monetary policy in the THANK model with capital. {#tbl-2}

Lastly, @tbl-3 shows the amplification of monetary policy for the RANK, TANK and THANK models with sticky wages.[^6] In the models without capital, we can see that the addition of sticky wages reduces the amplification introduced by the income inequality channel. This is because adding sticky wages removes the countercyclicality of profits - a key mechanism for the amplification of shocks in the TANK and THANK models.

[^6]: The model with sticky wages has two sources of nominal rigidities. This creates another break of money neutrality and leads to stronger monetary policy effects. Therefore, the RANK baseline for the sticky wages model features a larger consumption response than in the model with only sticky prices.

| | RANK | Heterogeneous Agents | | |
|---|---|---|---|---|
| | | No Y inequality | Y inequality | + Risk |
| no K | 1 | 1 (=RANK) | 1.01 | 1.02 |
| K | 0.94 | 1.53 | 1.77 | 1.95 |

: Amplification of monetary policy effects on consumption with sticky wages across RANK, TANK and THANK models with and without capital. {#tbl-3}

As was the case with sticky prices, capital inequality alone again introduces limited amplification of monetary policy. Comparing the TANK model with capital to the RANK model wit capital shows that capital inequality amplifies monetary policy by approximately 63% (the ratio $1.53 / 0.94$). This is comparable to the role of capital inequality in the sticky price case (the ratio $1.11 / 0.66$ shows amplification of around 68%).

Importantly, the key result that capital and income inequality are complementary is robust to the model with sticky wages. The amplification with both capital and income inequality is again greater than the product of the indivudal channels ($1.77 > 1.53 \times 1.01$). The complementary is again reinforced by the addition of idiosyncratic risk, with the THANK model with capital and income inequality generating amplification of 1.95.

#### Notes on the Literature

This chapter is based on Bilbiie et al. (2022). As mentioned in previous chapters, one of the earliest, seminal papers on TANK models focused precisely on physical capital as the asset the holding of which drove the distinction between optimizing agents and "rule of thumb" Galí et al. (2007); that meant that the analysis was a fortiori quantitative, since analytical solutions for models with capital are not easily available. The analysis here provides analytical tools to disentangle the separate roles of income inequality, investment, and MPC heterogeneity. A number of quantitative HANK models also feature capital investment, and therefore implicitly feature the capital inequality channel introduced in this chapter. In the Kaplan et al. (2018) HANK model with liquid and illiquid assets, the response of procyclical investment is a key driver of the consumption response to monetary policy shocks, see also Alves et al. (2020); this is also present in Bayer et al. (2019, 2024); Luetticke (2021); Gornemann et al. (2016); Hagedorn et al. (2019). Auclert et al. (2020) also include investment in an extension of their baseline HANK model, which they estimate—finding that this investment channel is a major contributor to aggregate fluctuations in their model. This model does however abstract from the cyclicality of inequality, meaning that the complementarity between procyclical investment and countercyclical inequality is not a feature of the model.

#### Summary

In this chapter, we covered an important extension of the THANK model developed in chapters 4 and 5. We showed that physical capital plays an important role in driving the consumption response to monetary policy. In particular, capital and income inequality represent two complementary channels delivering amplification though a 'multiplier of the multiplier'. Quantitative analysis of the THANK model with capital shows that the redistribution of physical capital and profits have key implications for the strength of monetary policy. These findings yield important insights for both optimal policy design, and for understanding the mechanisms driving the results of the literature on quantitative HANK models featuring capital investment.

# References

- Felipe Alves, Greg Kaplan, Benjamin Moll, and Giovanni L. Violante. A Further Look at the Propagation of Monetary Policy Shocks in HANK. Journal of Money, Credit and Banking, 52(S2):521–559, 2020. doi: 10.1111/jmcb.12760.
- Adrien Auclert, Matthew Rognlie, and Ludwig Straub. Micro jumps, macro humps: Monetary policy and business cycles in an estimated hank model. Technical report, National Bureau of Economic Research, 2020.
- Christian Bayer, Ralph Lütticke, Lien Pham-Dao, and Volker Tjaden. Precautionary Savings, Illiquid Assets, and the Aggregate Consequences of Shocks to Household Income Risk. Econometrica, 87(1):255–290, 2019. doi: 10.3982/ECTA14321.
- Christian Bayer, Benjamin Born, and Ralph Luetticke. Shocks, Frictions, and Inequality in US Business Cycles. American Economic Review, 114(5):1211–1247, 2024. doi: 10.1257/aer.20211386. Conditionally accepted.
- Florin O Bilbiie, Diego R Känzig, and Paolo Surico. Capital and income inequality: An aggregate-demand complementarity. Journal of Monetary Economics, 126:154–169, 2022. doi: 10.1016/j.jmoneco.2022.01.002.
- Olivier Coibion, Yuriy Gorodnichenko, Lorenz Kueng, and John Silvia. Innocent bystanders? monetary policy and inequality. Journal of Monetary Economics, 88:70–89, 2017.
- Jordi Galí, J. David López-Salido, and Javier Vallés. Understanding the Effects of Government Spending on Consumption. Journal of the European Economic Association, 5(1):227–270, 2007. doi: 10.1162/JEEA.2007.5.1.227.
- Nils Gornemann, Keith Kuester, and Makoto Nakajima. Doves for the Rich, Hawks for the Poor? Distributional Consequences of Monetary Policy. 2016. CEPR Discussion Paper No. DP11233.
- Marcus Hagedorn, Iourii Manovskii, and Kurt Mitman. The Fiscal Multiplier. Working Paper 25571, NBER, 2019.
- Greg Kaplan, Benjamin Moll, and Giovanni L Violante. Monetary policy according to hank. American Economic Review, 108(3):697–743, 2018. doi: 10.1257/aer.20160042.
- Ralph Luetticke. Transmission of Monetary Policy with Heterogeneity in Household Portfolios. American Economic Journal: Macroeconomics, 13(2):1–25, 2021. doi: 10.1257/mac.20190064.
- Paul A Samuelson. Interactions between the multiplier analysis and the principle of acceleration. The Review of Economics and statistics, 21(2):75–78, 1939.
